### ISSUE TITLE
Have Dynmap work with separate hosts with all features.

### ISSUE THREAD

**Issue by ZacharyDuBois** [webbukkit/dynmap#1135]
Could you add in the ability to have all of the features of the Dynmap plugins with separate hosts for the web server and Minecraft server. I use completely separate hosting companies and want to have dynmap upload the tiles upon them updating to my web server that can host the interface. I also want to be able to have the live player stats and stuff. I think that website stuff should stay with web servers and Minecraft stays with Minecraft servers.
- Thanks
  -- Zach

**Comment by FrozenBeard** [comment]
sorry to dig up a 2 year old topic, but most VPS's are running on small SSD's now, and were in need of a solution to save tiles etc on external servers, Im down for S3 & CloudFront.

Hell, Could I mount an S3 bucket on Debian and symlink the folder?

**Comment by pr4xt3roy** [comment]
@FrozenBeard If you are using AWS, could this be a workable solution? https://aws.amazon.com/blogs/aws/amazon-elastic-file-system-shared-file-storage-for-amazon-ec2/

**Comment by FrozenBeard** [comment]
@pr4xt3roy Im not using any AWS as of yet, I have a set of servers on a OVH VPS and my main server is still on a shared host, that Dynmap has a symlink to a HDD, but my tiny 40GB OVH SSD VPS Im trying to find a solution to move the Dynmap tiles to another location, I have many shared web-servers I could use if I could mount them, Never used AWS before, but im also looking into them as a backup solution too?

**Comment by ZacharyDuBois** [comment]
You could NFS it. That's what I did when I used this plugin. Initial render takes forever though. I use MC overviewer now.

**Comment by rfcMike** [comment]
Actually, since this was first opened, I've added support for map data to be stored in alternate places, based around an in-code storage driver (currently, there are drivers for 'normal' file system storage, MySQL database, and SQLite database).  I'll give a look at how practical doing an S3 driver would be, but I suspect it may not be that bad.

**Comment by mikeprimm** [comment]
Actually, since this was first opened, I've added support for map data to be stored in alternate places, based around an in-code storage driver (currently, there are drivers for 'normal' file system storage, MySQL database, and SQLite database). I'll give a look at how practical doing an S3 driver would be, but I suspect it may not be that bad.

**Comment by FrozenBeard** [comment]
@mikeprimm You can STORE the tile information in MySQL? Holy crap! I thought this was for settings or saving player movement information, I had no idea you can store images in MySQL! What kind of sizes are we looking at for databases now? I would imagine they are absolutely gigantic?

**Comment by mikeprimm** [comment]
The dominant space usage is pretty similar to file system - some improvement due to fragmentation overhead (e.g. file systems allocate space in chunks, not bytes), with some overhead in the DB encoding itself.  I haven't done a scientific A vs B comparison, but I'd wager its within +-10% of the same size, for a given map.  The upside is the DB server doesn't need to be the same box as the MC server, nor the web server.

**Comment by FrozenBeard** [comment]
I'm definitely going to give this a shot with my crappy shared hosting,
After I request an external IP connect. Does this have any downsides? Like
increased stress on the network/MySQL server? Does it do a tremendous
amount of read query's when using the map?

**Comment by Psy-Virus** [comment]
TL:DR

If still needed, pls reopen.
