### ISSUE TITLE
Tell progress of fullrender

### ISSUE THREAD

**Issue by xZise** [webbukkit/dynmap#140]
Is it somehow possible to inform you about the progress of fullrender? A simple line that it is one is really easy to miss.

Fabian

**Comment by ghost** [comment]
I'm necro-ing this issue, because I don't believe you. You say "we can't know how much more we need to do", but that's not true. The world files all exist, and you're accessing them to render the map. There's no reason you couldn't run a quick scan through all of the .mca files to count the number of chunks needed to render.

Sure, it might take a little extra time, but it's not like that really matters, because fullrender is already a several hour-long process. I personally wouldn't mind the extra couple minutes it could take to count the total chunks to render, so I've got an idea of the progress and can keep my players up-to-date on when they'll be able to join again (as running a full render with players on has never worked well for me).

You're gonna say, "but the minecraft world files could be infinitely large, so it would take forever look through all the chunks". That's how it already is with the fullrender, because it has to render an unknown number of chunks in the first place. Also, you could add a config to put a timeout on how long this initial scan may take before it's aborted. If you run out of time before you find all the chunks, just show the total number of chunks as "1000+" (1000 of course being replaced with the number of chunks that were discovered before it timed out.

Just because the data isn't provided to you doesn't mean it's impossible, or even difficult to do. Your response to this request seems like laziness more than anything.

Edit: I just want to take the time to say that I love your plugin and I appreciate the work you've put into it. I understand that you don't make money off the plugin, but honestly I'd be willing to pay for DynMap as a premium resource if it offered improved features.

I get that sometimes you get busy with life, but this post was 9 years ago, so I doubt you've not had enough free time since then.

**Comment by ghost** [comment]
Another thought I just had after posting this. You could even make an educated guess on the overall progress of a full-render based on the world size. Even that would be better than nothing. The 'pending chunks' diagnostics might be useful to you as the developer, but they're kinda useless to us as end-users.

**Comment by leahcornelius** [comment]
Agreed i :+1: this

**Comment by AlmosGH** [comment]
Bump. Do this please.

**Comment by Drake630** [comment]
Agreed, it would be nice to have a "XXX tiles rendered. Estimated tiles remaining: xxx" or similar.

**Comment by 3nt3** [comment]
+1

**Comment by Fefedu973** [comment]
👍 +1

**Comment by zmweske** [comment]
I know it's not exactly what people are looking for, but I found this command useful to at least know that things are moving (set up for a docker container):
`watch -c -n 0.2 docker exec -i minecraft_container_name rcon-cli dynmap stats`

For clarity, the key part is the `dynmap stats` . Of course, still no percentage complete or anything though

**Comment by dev-dakky** [comment]
Bumping to express my agreement with the ghost user's suggestion. Coming from a background of programming, yes exact answers may be impossible, but even having the total number of loaded chunks available as a "finished" goal would be useful. Counting ones already rendered in this total would be fine, would just mean the progress estimate jumps up a bit faster when encountering pre-rendered, unmodified chunks. If anything, progress bars moving faster here and there among a steady crawl is more satisfying than no progress bar at all
