### ISSUE TITLE
[Request] Carpenter's Blocks support

### ISSUE THREAD

**Issue by GregoriMarow** [webbukkit/dynmap#1517]
Hi,
Carpenter's Mod Blocks are invisible in dynmap.
I would be nice if it will be supported :)

Link to Mod Threat:
http://www.minecraftforum.net/topic/1790919-1516forge-carpenters-blocks-v202-slopes-stairs-and-more/

BTW: using dynmap for Forge.

**Comment by oliverkane** [comment]
Bump.  +1 for this.

**Comment by InsaneJ** [comment]
We've recently added Carpenter's Blocks to our public mod pack and would very much appreciate Dynmap support for it. If at all possible, please include support for it.

**Comment by oliverkane** [comment]
Is there a way we from the community could help with this?  I'd rather not be all like "do work for us!" and rather be like "show me how to help".  Love this mod and would be quite happy to contribute.

**Comment by wolf-girl** [comment]
i love this mod so much but i have exactly the same problem. whenever people on the internet get this and do mod reviews they never have a problem or mention one. if i could do anything to help this annoying glitch please let me know!

**Comment by wolf-girl** [comment]
when i have been looking on the internet i only found one thing that MIGHT help! i have noticed that all these people say they have optifine when i took it off mine it started to work. if none of you are using otifine i am sorry and i will look into it if you do then try removing it! i also had this problem with build craft dynamic transport and several others but when i take optifine out it work perfectly!

**Comment by oliverkane** [comment]
@wolf-girl , the client uses Optifine. The server will use Dynmap. These are never in the same environment.

**Comment by wolf-girl** [comment]
sorry cant find anything to stop it in Dynmap but i will try and find something, sorry!

**Comment by mikeprimm** [comment]
Carpenter's Blocks on which MC versions?

**Comment by InsaneJ** [comment]
Minecraft 1.7.10 please.

**Comment by GregoriMarow** [comment]
1.6.4 please

**Comment by Razorskills** [comment]
1.7.10! I noticed in the log it says:
[19:47:22 INFO]: [Dynmap] CarpentersBlocks[3.3.5] models enabled

:) but my map shows otherwise lol

**Comment by mikeprimm** [comment]
Supporting the REAL blocks in this mod is going to be non-trivial - custom code, versus just custom model definitions.  The ModScraper derived models just handle a few of the simple models.

**Comment by DarthPJB** [comment]
Is there some simple mechanism to change the render of these blocks?
At the moment many of them render simple as redstone - If I was able to at the least render them as Stone, or better still as the applied texture of the model, the visual improvement would be dramatic.

Perhaps something I could create a patch for - if you can point me in the general direction of the methods handling such queries.

**Comment by TheQuantumGeneral** [comment]
Not sure if the input matters but this would definately be an amazing thing. Even if slopes rendered as stairs this would be great.

**Comment by DarthPJB** [comment]
I have to agree with TheQuantumGeneral - anything is better than redstone, even solid blocks.

**Comment by wbattel4607** [comment]
+1

**Comment by chrisj165** [comment]
+1 needs 1.6.4 support would be awesome.

**Comment by ErebusAres** [comment]
1.7.10 :+1:

**Comment by twistedatoms** [comment]
1.7.10 :+1:

**Comment by Razorskills** [comment]
1.7.10 :+1:

**Comment by InsaneJ** [comment]
We have recently started playing the HappyDiggers AMP mod pack for Minecraft 1.5.2 again. A lot of things in 1.5.2 run a lot better on slower computers than 1.7.10 so for a lot of people in our community that's great.

I know 1.5.2 is pretty old. But I'd like to ask if you'd consider supporting it a little longer still and add support for Carpenter's Blocks for it. Thanks!

**Comment by Flenix** [comment]
Adding my request to this too. In the mean time I'll try and get something a little better than redstone, but reading the inventory of the block and using the contained itemblock for the texture shouldn't be impossible...

Does Forge Dynmap have an API like the bukkit one? If so, I could possibly make a bridge mod which would add support for this, with the right documentation.

**Comment by Flenix** [comment]
For getting the default carpenters texture on the block, it's incredibly easy. No idea why it uses redstone right now, but just replace the line that starts the same in CarpentersBlocks-textures.txt with this, and it will use the carpenters wooden cross:

texture:id=minecraft/redstone_dust_cross_overlay,filename=assets/carpentersblocks/textures/blocks/general/full_frame.png

No need to rename the ID, that's just local use, it's the filename that matters.

**Comment by ErikSteiner** [comment]
Hey guys, I am wondering what had happened since the request was made. I use Minecraft Forge 1.7.10 10.13.4.1558 and Carpenter's Blocks v3.3.8_dev_r8. While I have a look at my Dynmap I can only see red lines for my Carpenter's Blocks: http://i.imgur.com/GVAq2ee.jpg.

Is there anything I can do? Btw. yes I use a custom resource pack and I do not understand the note of Flenix..

**Comment by Flenix** [comment]
Erik, go to ./dynmap/renderdata/custom, find the file called CarpentersBlocks-textures.txt

Then, find the line that starts as texture:id=minecraft/redstone_dust_cross_overlay, and replace the WHOLE line with the line I put in my comment before.

It isn't real carpenters support, but it shows the untextured frame that you get when you place carpenters by default - so at least people viewing the map know that's what it is.

**Comment by ErikSteiner** [comment]
Thank you for your reply. This is exactly what I don't understand. I use Dynmap-2.2-forge-1.7.10.
If I navigate to dynmap\renderdata there is no sub-folder called custom. There is only a folder called modsupport. The folder renderdata is empty except one file called readme, the folder modsupport is emtpy, too.

**Comment by Flenix** [comment]
Then technically you shouldn't be able to see any mod blocks at all... Because that's where Dynmap defines them. That is very weird.

Unfortunately that's about as much help as you'll get. The dev is very rarely around to respond to issues, I've been trying to get a marker one sorted for over a month now. Your best bet is just look through and find the files which may be elsewhere due to you using a custom texture pack

**Comment by ErikSteiner** [comment]
Ok I found out that these files for mods were in the jar file. I found the redstone_dust part thanks!

**To the request here for supporting Carpenter's Blocks**:
I played a little bit around with the texture and model file and I haven't found a way to reach a simple goal. So I tried to display Carpenter's Stairs correctly. I altered the model and texture file to use the renderer for stairs and gave the model the typical frame texture. Then I had a look into Dynmap and it was working, these blocks were stairs now, but the orientation was for all stairs the same. No matter what direction you saw ingame, dynmap displayed them all in the same way.
[](http://i.imgur.com/aLk1CAP.jpg)

The picture shows my experiment. The upper left circuit shows stairs that are not rendered, because they have another metadata. I only wanted to show cobblestone stairs, so this was correct. Then the right circuit and the one down below shows the stairs that are shown correctly but with a wrong orientation.

As far as I can tell this is a problem of the stairs renderer, because it will only work with different metadata. So before I excluded all other types of stairs, stairs of other materials had a different orientation. The problem is that the orientation is stored in the tile entity of the block. Dynmap can read those TAG's if you have a look at the textureIndex value for the renderer:
[](https://github.com/webbukkit/dynmap/wiki/Class-org.dynmap.hdmap.renderer.StairBlockRenderer)

Somehow one should be able to tell Dynmap that it should have a look at the cbMetadata of the stair block and get the orientation for the block. This is out of my knowledge, I was not able to manually alter the orientation of the stairs, so I don't know if the TAG-Procedure could work.

So this is the main problem for supporting this pack and it makes no sense to continue any work here until there is a solution for this.

**Comment by Mattrock607** [comment]
I would like to add to the chorus here and request support for Carpenter's blocks in 1.7.10. My server will someday update to 1.10.2, whenever Carpenter's Blocks, Buildcraft, and a few other mods update, but in the meantime it would be great to see this working. I'd be willing to help however I can though outside of modeling (I'm making a content pack for Flans) I'm not sure how I could be of service.

**Comment by Kundello** [comment]
Sooo what about carpenter blocks support in 1.7.10? Bug since 2014 :D

**Comment by Psy-Virus** [comment]
The Dev of Carpenter's is not really active anymore. But I'll put this on the list.
