### ISSUE TITLE
Support new chisel 

### ISSUE THREAD

**Issue by ActiveBaby** [webbukkit/dynmap#1671]
Hello. Can you add support new chisel for 1.7.10.

Problem - http://pastexen.com/i/tLmkeIxl4H.png
Chisel - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294901-chisel

Ty.

**Comment by SharkROAR** [comment]
Would absolutely love chisel support

**Comment by axelpx** [comment]
chisel support, even the basic one, would be so cool

**Comment by NoireMann** [comment]
I double this, we are heavily need Chisel 2 (not Chisel 1!) support for Dynmap!

That would be cool, btw!

**Comment by Zehir** [comment]
I'll take care of creating the configuration files for the blocks of chisels. Then I would make a pull-request.

**Comment by Zehir** [comment]
I have made a first config file generated using a custom script. I will post it later.
If someone want try my first config file, you can download it here: http://pastebin.com/gTKBUauc

**Comment by sbrandsborg** [comment]
it might be a stupid question, but what do you do with the config file? cant figure where to put it

**Comment by Zehir** [comment]
You need to put it here: SERVER_ROOT/dynmap/renderdata/chisel-texture.txt

**Comment by NitroxydeX** [comment]
@Zehir tried your file - works good but not perfect. e.g. Slabs and Stairs are not rendered.

**Comment by Zehir** [comment]
I do not have much time to work on it but here's the script I did if you wish to contribute.
You'll find it on my repo:
https://github.com/Zehir/Dynmap-Chisel-2-Config

**Comment by Patrick1005de** [comment]
The chisel-textures.txt doesn't work on my Server.. :(

**Comment by vlad20012** [comment]
Configs generated by DynmapModScraper:
[chisel-models.txt](https://github.com/webbukkit/dynmap/files/679635/chisel-models.txt)
[chisel-texture.txt](https://github.com/webbukkit/dynmap/files/679636/chisel-texture.txt)

**Comment by Dooglesmile** [comment]
Hi thanks for these configs, I'm having trouble tweaking them to work with the latest MC1.12.2 versions though. 
I'm using Chisel-MC1.12.2-0.2.1.35 with Dynmap-3.0-beta-1-forge-1.12.2 and DynmapBlockScan-3.0-alpha-2-forge-1.12.2.
There are a lot of differently named blocks in the newer version of chisel, along with many that no longer exist.
Also, the blockscan mod doesn't detect any blocks or textures when scanning the chisel mod, unlike when it scans others such as tinkers construct.

This is all that appears within the chisel-models.txt and chisel-texture.txt files after scanning:
`
modname:chisel
customblock:id=%auto_chisel,data=0,class=org.dynmap.hdmap.renderer.CuboidRenderer

modname:chisel
block:id=%auto_chisel,data=0,transparency=TRANSPARENT,stdrot=true
`
Is there any way I could maybe assign a default texture to the chisel blocks so that on the map I don't have black squares in 2D and floating structures in 3D views?

**Comment by BonaireDreams** [comment]
Has anyone had any luck getting chisel blocks to show? I've even tried with block-id-alias without any luck. Trying to get the pyramids in Pyramid Reborn 3 to show, even if they are all just plain sandstone.

"chisel:sandstoneyellow": "minecraft:sandstone"
"chisel:sandstoneyellow1": "minecraft:sandstone"
"chisel:sandstoneyellow2": "minecraft:sandstone"
"chisel:sandstone-scribbles": "minecraft:sandstone"
These did not work.
Still have nothing but black for all chisel blocks.
![image](https://user-images.githubusercontent.com/5133282/46986132-96ea0a80-d0a2-11e8-818e-4f108206166c.png)

**Comment by nate2014jatc** [comment]
Why was this closed? It doesn't seem to be resolved, or even have a workaround mentioned.

**Comment by Psy-Virus** [comment]
Read the Labels
