### ISSUE TITLE
[Request] add rotation to 3D view

### ISSUE THREAD

**Issue by kreezxil** [webbukkit/dynmap#1758]
Mike I've been following and using  your dynmap since 1.4.7 and one thing I've always found lacking is a rotateable 3D map. Is it a possibility?

**Comment by Psy-Virus** [comment]
Hey @kreezxil, cool that someone is also thinking about rotatable maps.

I've mentioned this in #1688 before. But no response from @mikeprimm since then...

Is #1688 in that direction? At the moment it's also possible to have it ~rotatable. But you've to render the complete map for any view... 

cheers

**Comment by kreezxil** [comment]
Your idea is way cooler than mine. Also I found the perspectives thing and thought maybe that's why he hasn't really pursued the easy 3d GUI idea with rotatable maps.

-----Original Message-----

**Comment by Psy-Virus** [comment]
Already listed
