### ISSUE TITLE
[request] /whitelist on to disable map chat

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#1766]
There is nothing more infuriating than turning on the whitelist for maintenance and having people spam the map asking why they cant log on, Having the map chat toggle off when the whitelist is on would save many server admins heads from exploding.

**Comment by Psy-Virus** [comment]
You could also disable the ability to Chat while in maintenance.

**Comment by FrozenBeard** [comment]
So staff can't talk while in maintenance? Good solution /s

**Comment by Psy-Virus** [comment]
There's Discord, TeamSpeak and various other communication methods. I don't think Dynmap will ever replace social platforms.
But maybe there's a scenario I didn't think of.
But on one hand you write something about the white list. So I assume you'll have the MC-Server running. And if the staff will be able to login due to being white listed, means that they can also talk over the ingame chat.

So What do you want to achieve?

**Comment by FrozenBeard** [comment]
We have a staff chat, but if you are testing in-game doing maintenance in-game, you tend to talk, in-game. this should not be broadcast public if you are in maintenance or testing. we mostly have an admin chat now, but you cant give that to players if they are helping test.
