### ISSUE TITLE
[documentation request] Please publish specifications for JSON update feed

### ISSUE THREAD

**Issue by AnrDaemon** [webbukkit/dynmap#1788]
Good time of the day to you.
I've convinced one of the developers of Miranda-NG to write a chat support for your addon's web chat.
We've managed to research enough of the protocol details to get the basic functionality going, but it would be wery useful to have official specifications posted somewhere. Less guesswork = better programs.

**Comment by Psy-Virus** [comment]
If this is still relevant, please reopen or create a new issue with updated details.

**Comment by AnrDaemon** [comment]
Is there an existing documentation I've missed?

**Comment by Psy-Virus** [comment]
We're currently in the process of consolidating the issues because they gathered up to a 700 with most of them resolved, fixed but never closed or inactive users. There will be a forum in the near future to handle those support questions. Please keep an eye on the sites where Dynmap is present to get the link for it when it's online.

I also tagged the issue with "Doc improvement" and will list it. I mean u were waiting since years so a few days or weeks won't matter, are they? :P

**Comment by Psy-Virus** [comment]
Oh and btw. If you have useful information about this stuff and want to share it. This will also be a great place to do so :)

**Comment by AnrDaemon** [comment]
Yes, I greatly appreciate the cleanup. 600+ open issues is "a bit" too much for my taste.
But regarding sharing information, I'm afraid, anything I've had 3 and a half year age would be quite stale by now.
