### ISSUE TITLE
Zoom out black on map

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#1796]
Rendered a small 500 radius area on my map and on the zoom out level everything i black, but when zoomed in the tiles will show up.
See screenshot, for some reason the outline of the area i tried rendering came up fine. Everything inside it is also rendered just not when zoomed out
![screen shot 2015-06-18 at 17 57 21](https://cloud.githubusercontent.com/assets/11436172/8236912/a34124bc-15e3-11e5-915b-3ca0748b6531.png)

http://188.165.244.85:6969

**Comment by gigapouch** [comment]
Did you fill in the empty chunks with a plugin like WorldBorder?

**Comment by Cpt-Beefheart** [comment]
I didn't use that so I don't know.  If you have the dynmap trigger for chunk generating on, just spend a session flying the black route and as they generate they will go into your tile render queue.

**Comment by motheman** [comment]
Not using world guard or anything.

**Comment by motheman** [comment]
Loading the chunks into the queue hasn't done anything. Can someone explain the naming convention for the .png files to me? i am trying to go through and delete the files for these chunks but can't find em

**Comment by Cpt-Beefheart** [comment]
Let me see your map.  Was the full render even done yet?

**Comment by motheman** [comment]
link is in the original post 

http://188.165.244.85:6969

it was just a radius render

**Comment by Cpt-Beefheart** [comment]
Ah sorry, I thought you were the guy with the black rings in the surface map.. but that is a fresh patchy surface map so I guess nevermind

Date: Mon, 22 Jun 2015 19:26:15 -0700

**Comment by Cpt-Beefheart** [comment]
You may also want to add Worldborder to your plugins, you have weird exploration trails to the south east out to 50,000 block range

Date: Mon, 22 Jun 2015 19:26:15 -0700

**Comment by motheman** [comment]
I don't want a world border though. I think you're getting off the point a little bit, no offence.

The issue is that dynmap doesn't render render the zoom out tiles correctly. 

I have also noticed this being an issue whenever the server restarts, however in this case there wasn't a restart.

Do you know how the folders are sorted in the file tree system for the .png files. I would like to manually go through and delete ones i am having issues with

**Comment by Cpt-Beefheart** [comment]
Sorry that is weird for sure.  I don't know how the folders are sorted, but looking at your surface map you've already deleted a bunch so maybe just start fresh and clean?

Is performance a factor? No offence intended whatsoever but that map is quite laggy. Is your ram being overloaded? Did you set the configs involving cpu cores correctly?
I do really want to help, but I need to see the configs to stop all the guessing:p.  If you send them to satsun1@hotmail.com I will compare with my own line by line.  Be sure to include the template you are using for your normal worlds please.
Regards,

**Comment by motheman** [comment]
No offence taken. 

i did another radiusrender on the area that was black and the tiles seemed to have come back fine. Not sure what is different now. 

As for the lag it's set up fine and RAM isn't sweating. I believe it will be the network drive i'm using at the moment, didn't expect the map to take this much space. 28GB already

**Comment by Cpt-Beefheart** [comment]
Hehe mine is 10k radius and round, and the map is close to 100gb, with square yours will be larger.
Maybe you don't notice the map lag because of being on or next to your host machine?  Here is my map, server is still white listed ATM while finishing touches on admin structures done.

158.85.102.108:8223

Yes night view is weird ATM, I am in process of re rendering the map with my texturepack.  Just doing it in a grid pattern with 1000 block radius renders at a time to not bog things down for players.

**Comment by motheman** [comment]
looks sweet

**Comment by gigapouch** [comment]
Mine is 10k by 10k square and it's only 4 GB.

**Comment by Cpt-Beefheart** [comment]
Is it black and white and have no details :p

**Comment by motheman** [comment]
bump as this is reocurring issue. 
Also some parts that are working on the map don't show new blocks that have been placed zoomed out.
Possibly a bug in the zoom out rendering process?

**Comment by gigapouch** [comment]
No, it's perfectly detailed.

**Comment by Cpt-Beefheart** [comment]
Sorry man, still just looks like your render was stopped early.  I'd still love to help but would need to see all the dynmap config files you have in play.   Add me on skype (cpt_beefheart) and this week sometime we'll get it going right.

**Comment by gigapouch** [comment]
Me? 


     On Wednesday, July 1, 2015 8:36 AM, Cpt-Beefheart <notifications@github.com> wrote:
   

 Sorry man, still just looks like your render was stopped early. I'd still love to help but would need to see all the dynmap config files you have in play. Add me on skype (cpt_beefheart) and this week sometime we'll get it going right.—

**Comment by Cpt-Beefheart** [comment]
No giga, your issue is a different thread, this is motheman's.

**Comment by motheman** [comment]
so if the render did get interrupted or stopped early, there is no way for tiles to be rendered in zoom out mode? Other than restarting i guess?

**Comment by magneticflux-** [comment]
I'm having this exact same issue, running on Forge 1.12.2. @Cpt-Beefheart did this ever get resolved?

**Comment by Psy-Virus** [comment]
Even if this was last commented this year, I consider this issue to be too old. If this issue is still relevant, please open a new one with updated details and the use of the latest Dynmap versions found [here](http://www.dynmap.us/builds/dynmap/)
The always last versions for -
Forge: Dynmap-HEAD-forge-X.X.X.jar
Bukkit/Spigot; Dynmap-HEAD-spigot.jar
