### ISSUE TITLE
How do I set a texturepack?

### ISSUE THREAD

**Issue by Janeke100** [webbukkit/dynmap#1797]
Hey, I've googled it plenty of times and have found 2 ways to do it. either edit shaders.txt or custom-shaders.txt. either way it isn't showing on the map. could someone please give very clear instructions for a plugin idiot like myself? thanks in advance!

this is how it is set now:
(removed some hashtags because they mess things up)
shaders.txt:
# 

This file contains default standard shader definitions.  The contents of this file are replaced and updated
during upgrades, so new or updated shader definitions should be done in the custom-shaders.txt file
# 

shaders:
   Default shader - used if shader not specified or invalid
- class: org.dynmap.hdmap.TexturePackHDShader
  name: Conquest_1.8.zip
  texturepack: Conquest_1.8.zip
  
  Color scheme based shaders
- class: org.dynmap.hdmap.DefaultHDShader
  name: defaultscheme
  colorscheme: default

custom-shaders.txt:
 The user is free to add new and custom shaders here, including replacements for standard ones
 Dynmap's install will not overwrite it
shaders:
- class: org.dynmap.hdmap.TexturePackHDShader
  name: ConquestTexturepack
  texturepack: Conquest
  biomeshaded: true
  better-grass: false
  grid-scale: 0

**Comment by Cpt-Beefheart** [comment]
I did mine last week so is fresh in memory.  There are three steps:
1) Edit custom or normal shader txt:
shaders:
  -
    class: org.dynmap.hdmap.TexturePackHDShader
    name: servercustom (or whatever)
    texturepack: whatever.zip

2) edit whichever template is being used for that map, change the shader line to be 
shader: servercustom (or whatever)

3) add the zip to the texturepack folder

Then reload/restart, radiusrender a small area to see if changed.
I think that is complete..hopefully
Regards,

**Comment by NatoBoram** [comment]
> edit whichever template is being used for that map

And how do we do that?

**Comment by NatoBoram** [comment]
If anyone still wants to know how to apply a texture pack, I've got you covered [here](https://www.reddit.com/r/admincraft/comments/9gr3wx/how_to_apply_a_resource_pack_to_dynmap/e66bfrx).

**Comment by NatoBoram** [comment]
Because this link is amongst the first results for this question, let me just paste the steps here.

---

Basically, you want your Resource Pack to OVERRIDE the standard one. How you do that?

```bash
nano plugins/dynmap/custom-shaders.txt
```

This will create a new `custom-shaders.txt` because changing the default config is a bad idea and this will override the defaults.

```yaml
shaders:
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture
    texturepack: Faithful+1.13.1-rv1.zip
```

`stdtexture` is the name of the standard textures. By doing that, everything that would normally use `stdtexture` (aka pretty much everything except minor details like rivers) will now use `plugins/dynmap/texturepacks/Faithful+1.13.1-rv1.zip`. Of course, you can use your own. This is just the quickest way to go home.
