### ISSUE TITLE
Wrong username shown on web chat

### ISSUE THREAD

**Issue by JayAvery** [webbukkit/dynmap#1798]
When sending a message from the web chat on dynmap, the username is wrong. For some reason, any message sent from webchat will come up under one particular player's username, no matter what - regardless of who is actually sending it, sending from different computers, etc. Am I missing some obvious setting or something?

**Comment by Tayrtahn** [comment]
By any chance, are you all connecting from within the same network (like in the same house, the same university, etc)? Two players on my server live in the same house and often show up with each other's usernames when posting from web chat.

I believe this is because they appear (to the server and the outside world) to have the same IP address. There are settings related to requiring users to log in to web chat, instead of relying on their IP. I haven't taken the time to change them, but it should be fairly simple.
