### ISSUE TITLE
[Request] Enable gzip compression on web server

### ISSUE THREAD

**Issue by ataranlen** [webbukkit/dynmap#1800]
https://developers.google.com/speed/docs/insights/EnableCompression

The dynmap pages that I have on my website are the worst offenders for my page speed metrics. Google's analysis says enabling compression could reduce over 75% of the bandwidth usage of Dynmap for some files. (PageSpeed insights gives Dynmap a 48/100 on desktop, as compared to 98/100 on my homepage)

Alternatively, minifying the Javascript used by Dynmap could reduce used bandwidth by over 25%

And finally, enabling caching on resources could save untold volumes of bandwidth, even if it is set only for some resources.

**Comment by ataranlen** [comment]
Another suggestion for bandwidth heavy servers would be enable some sort of support for https://github.com/pornel/pngquant

**Comment by rautamiekka** [comment]
While not totally dead idea, it increases CPU usage alot and latency between request for a pic and delivered rises at least 2½x.

**Comment by Psy-Virus** [comment]
Most of this could be achieved by using an external server like Apache. The internal server should be kept as small and resource saving as possible because Dynmap's rendering is already resource intensive.
But this is something that could be written into a Tips and Tricks Section of the new forum that will go online in the near future. So please consider writing it down there. :)

Thanks
