### ISSUE TITLE
Dead bushes are following me

### ISSUE THREAD

**Issue by magonreal** [webbukkit/dynmap#1804]
I have a weird problem with Dynmap-Mod-Implementation. I used the ModScraper to get Textures for Railcraft. The normal blocks render perfecetly. Just like i wanted it ;)
But now i am leaving a trail in Dynmap of what looks like dead bushes. They are not visible in Minecraft and are even generated in mid air. They decay after a time, but are really ugly. Maybe someone can help me with this?

I am only running:
forge-1.7.10-10.13.4.1448-1.7.10-universal,
Dynmap-2.2-alpha-2-forge-1.7.10, and
Railcraft_1.7.10-9.6.1.0.

I used the DynmapModScraper-2.1-alpha-1-forge-1.7.10 to get the textures.

![2015-06-30_23 10 36](https://cloud.githubusercontent.com/assets/13124998/8442203/d20fd718-1f7d-11e5-8430-fafaa3c5aaf0.png)
![dynmap_screenshot](https://cloud.githubusercontent.com/assets/13124998/8442204/d2294fe0-1f7d-11e5-8d6d-e95f89026996.PNG)

**Comment by Tayrtahn** [comment]
I'm just guessing here, but I suspect that those are Railcraft's "residual heat"/"tracking aura" blocks. They're somewhat infamous for causing problems with other mods, since they're not air but act a lot like air...

The scraper probably picked them up and tried to find a way to render them. You should be able to disable them in the file from the scraper, but you may just want to disable that feature of Railcraft altogether, since it's generally more trouble than it's worth.

**Comment by magonreal** [comment]
Thank you!
That totally solved the problem!
I disabled the Railcraft blocks in the Railcraft config and now everything works fine :)
