### ISSUE TITLE
Incomplete render with Spigot 1.8.8

### ISSUE THREAD

**Issue by EvilOlaf** [webbukkit/dynmap#1814]
Just updated to 2.2 from 2.1  of Dynmap as well as to Spigot 1.8.8 from 1.8.7 and notice that several chunks are not being rendered at fullrender/radiusrender:
http://www0.xup.in/exec/ximg.php?fid=95592271

First I thought that was an issue with 2.2 and stept back to 2.1, issue persisted after purgeworld and fullrender.
Downgraded from Spigot 1.8.8 to 1.8.7 (the world has been generated in 1.8.8), issue persisted after purgeworld and fullrender.

Generated a new world with 1.8.7 and dynmap 2.1 and did a fullrender, the issue disappeared, world rendered perfectly fine.

Last thing I tried was using dynmap 2.2 with Spigot 1.8.7: No issues.

So there seems to be an issue with dynmap at all when using Spigot 1.8.8 (and a 1.8.8 generated world), but for me I have no idea if this is a fault on dynmaps or Spigots end.
The 1.8.8 world had no physical issues like missing chunks, checked several of these "black holes".

For now i stay at 1.8.8 with dynmap 2.2 and hope that this could be fixed one day :D

**Comment by wonsnot** [comment]
I am having the same problem.

**Comment by Psy-Virus** [comment]
Is it only on "zoom-out-tiles"?

So if you zoom all the way in, do they appear?

Did you delete all tiles before a fullrender?

**Comment by EvilOlaf** [comment]
Interesting. Didn't check the map for a while now. 
Seems like a couple of them disappeared, some are still there.

A 4 by 2 unrendered block of chunks disappeared after zooming in, smaller 1x1 black holes still there on all zoom levels.

**Comment by wonsnot** [comment]
@Psy-Virus It happens at all level of zoom. I haven't tried to delete all tiles yet.
My map for reference: http://24.116.240.173:8123/
A couple of us on the server have walked from one of the larger rendered areas to the other multiple times and it hasn't updated.
I am currently running the latest version of minecraft server, Spigot, GriefPrevention v11.9, and dynmap.

**Comment by Psy-Virus** [comment]
At the moment it looks like your rendering is incomplete. What does `dynmap stats` and `dynmap triggerstats` report?

did you restart your server while the rendering was active?
The thing is: If you don't do an initial fullrender (`dynmap fullrender world x z`) all chunks that get activated, due to a user who walks through and triggers physics, relightning and so on are added to the backlog and Dynmap will process them 'till the backlog is empty; except you have to many players on your server or the performance drops too hard. (Look into the config.txt around line 350-370)

So for a clean result: Delete the whole map (<b>that means deleting all files and folders within your Dynmap-tile-directory</b> for example: `server/plugins/dynmap/tiles`)
Then do a `dynmap fullrender world x z` from console or a `/dynmap fullrender` from the ingame chat.

If your issue reappears after you've done this, you have a problem, if not, something went wrong while your backlog was full. Maybe you've restarted your server and Dynmap forgot to save the backlog or you forgot to set the option. :-)

Oh and maybe you should compile the spigot build of the day and download the dev version of Dynmap from [>>here<<](http://mikeprimm.com/dynmap/builds/dynmap/dynmap-HEAD.jar)

**Comment by Psy-Virus** [comment]
Oh and please put your results within 
```text
html: <code>your text</code>
or
GitHub Markdown: `your text`
```

**Comment by wonsnot** [comment]
You fixed me. I deleted everything and did a fullrender and it is loading like it should as far as I can tell.

**Comment by Psy-Virus** [comment]
Perfect, pls don't forget to close you issue :+1: 

You can reopen it, if it's needed. :-)

**Comment by Psy-Virus** [comment]
And for the future, try to not restart your server while the backlog is filled ;-)

**Comment by EvilOlaf** [comment]
Did `dynmap purgeworld Farm`.
Then `dynmap pause all`.
Removed physically all remaining files in `Farm` folder.
`dynmap fullrender` from ingame so no further arguments needed.
`dynmap pause none` to continue rendering the other worlds.

stats.
```
[21:22:16 INFO]:   Farm.flat: processed=3620, rendered=3620, updated=2265, transparent=0
[21:22:16 INFO]:   Farm.t: processed=3315, rendered=3315, updated=2212, transparent=0
[21:22:16 INFO]:   Survival.flat: processed=11030, rendered=11030, updated=4908, transparent=0
[21:22:16 INFO]:   Survival.t: processed=10492, rendered=10492, updated=6295, transparent=0
[21:22:16 INFO]:   city.flat: processed=1237, rendered=1237, updated=314, transparent=0
[21:22:16 INFO]:   city.t: processed=1352, rendered=1352, updated=502, transparent=0
[21:22:16 INFO]:   events.flat: processed=6311, rendered=6311, updated=5300, transparent=162
[21:22:16 INFO]:   events.t: processed=4243, rendered=4243, updated=1783, transparent=574
[21:22:16 INFO]:   TOTALS: processed=41600, rendered=41600, updated=23579, transparent=736
[21:22:16 INFO]:   Triggered update queue size: 121 + 24
[21:22:16 INFO]:   Active render jobs: Farm 
[21:22:16 INFO]: Chunk Loading Statistics:
[21:22:16 INFO]:   Cache hit rate: 38.18%
[21:22:16 INFO]:   Chunks processed: Cached: count=1022047, 0.00 msec/chunk
[21:22:16 INFO]:   Chunks processed: Already Loaded: count=544253, 0.82 msec/chunk
[21:22:16 INFO]:   Chunks processed: Load Required: count=937080, 1.79 msec/chunk
[21:22:16 INFO]:   Chunks processed: Not Generated: count=173883, 0.00 msec/chunk
```

triggerstats
```
[21:23:55 INFO]: Render Trigger Statistics:
[21:23:55 INFO]:   blockbreak: calls=140162, calls-adding-tiles=7988, tiles-added=12019
[21:23:55 INFO]:   blockfade: calls=4560, calls-adding-tiles=1260, tiles-added=2197
[21:23:55 INFO]:   blockform: calls=1235, calls-adding-tiles=277, tiles-added=498
[21:23:55 INFO]:   blockgrow: calls=37520, calls-adding-tiles=14755, tiles-added=24683
[21:23:55 INFO]:   blockplace: calls=38310, calls-adding-tiles=3960, tiles-added=6201
[21:23:55 INFO]:   blockspread: calls=10662, calls-adding-tiles=4738, tiles-added=8499
[21:23:55 INFO]:   chunkpopulate: calls=77, calls-adding-tiles=49, tiles-added=268
[21:23:55 INFO]:   entityexplode: calls=77, calls-adding-tiles=71, tiles-added=236
[21:23:55 INFO]:   leavesdecay: calls=32150, calls-adding-tiles=1814, tiles-added=2849
[21:23:55 INFO]:   pistonretract: calls=66583, calls-adding-tiles=146, tiles-added=231
[21:23:55 INFO]:   structuregrow: calls=1502, calls-adding-tiles=1160, tiles-added=4340
``` 

I'll update here as soon I have visible results on the map.

**Comment by Psy-Virus** [comment]
Yepp, but my experience is, that this save-backlog-for-restart-thing is not perfectly reliable. Some times I lost my backlog after two restarts;
explored map, backlog filled, server restart, all okay - backlog is there, another restart, backlog was gone.
Then also after one or three.. and so on. 
But if that happens, I'm using the `dynmap updaterender world x z` and all is great^^

Back to topic:
It seems, that you didn't clear the backlog. So all tiles that are in the backlog will interfere with the fullrender process and slow it down because dynmap is working on the fullrender and also tries to add new generated calls.

Try:
```text
1. dynmap cancelrender farm
2. dynmap pause all
3. dynmap purgequeue
4. dynmap resetstats
5. dynmap purgeworld farm
6. Shut down your server and delete all within your tiles directory.
7. start your server after all is deleted
8. dynmap pause none
9. dynmap fullrender farm 0 0
```

I hope I didn't forget anything^^

**Comment by EvilOlaf** [comment]
Aight. I made these step by step (the tiles folder of the world was empty already, so everything has been purged properly) and the missing spots are still missing.
Quite uncomely new behavior ^^. Hope that get's fixed somehow as on 1.8.7 it worked like a charm.

**Comment by wonsnot** [comment]
Is there any chance you could post the link to your map? It seemed that it really helped fixing my problem, maybe it can help with yours.

**Comment by EvilOlaf** [comment]
Sure: http://144.76.33.47:8123/
Check world `Farm`. Nicely visible at the north border of the world.

**Comment by Psy-Virus** [comment]
Hey guys, I've tried the same. I've rendered a map in hires with latest spigot @ time of writing and latest dynmap @ time of writing. Nothing else. So maybe it's a plugin that you're using. Or a defect HDD... it could be anything^^

But for me it looks primary that dynmap isn't the evil guy in this story...

Maybe you should try with a clean server. only spigot and dynmap with the old configs. If it's happen there, you should double check your configs. If not, something on your current server is interfering with dynmap.

**Comment by EvilOlaf** [comment]
May thinking was similar in looking for the cause, but I decided to report this to dynmap first as I have an account here and not at the nexus yet ;)

It is weird, cause it seems to work well with 1.8.7 generated worlds but doesn't with 1.8.8.

Probably not an HDD issue as this would be logged at `dmesg` or syslog etc.

I'll give a clean server a try when I find time.

**Comment by Psy-Virus** [comment]
Btw, it was a 4k by 4k map. So ~62 500 chunks without any error

**Comment by Psy-Virus** [comment]
Okay, would be nice if you keep us updated, if you find a solution :-)

**Comment by wonsnot** [comment]
Stupid question, but have you gone out in game to these holes and checked them out personally?
I am by no means an expert, but it looks like unrendered chunks, maybe it is on the minecraft server side, and not dynmap that is having a problem.

**Comment by EvilOlaf** [comment]
Yes, as written above
`The 1.8.8 world had no physical issues like missing chunks, checked several of these "black holes".`

**Comment by EvilOlaf** [comment]
This might be a stupid question from my side but is there anything special to think of when running Spigot on MS Windows?
Just tried to run a blank server with WorldBorder and Dynmap only but when trying to open `http://localhost:8123` it just gives me after some loading

```
Directory: /

tiles/ 	65536 bytes 	10.08.2015 18:43:01
```

Tried to redownload the plugin, but it was complete.

**Comment by Psy-Virus** [comment]
Interesting... Do you use the internal or an external Web server?

**Comment by Psy-Virus** [comment]
But for testing, pls try it with your computers ip and not localhost.

**Comment by EvilOlaf** [comment]
As written I got it work by reseting the whole configuration to default.

Also the render seems to work as expected. 
Hard to believe that a plugin could cause the interferences...

**Comment by Psy-Virus** [comment]
Yeah, the problem is that post updates are not automatically updated ;-) That's why I said before, make a new post :-D

But if both plug ins try to use the same ressources @ the same time, it could happen that something goes wrong.. especially on spigot, because as far as I know, spigot is extremely trimmed to performance, so some debugging actions or anything in this direction are maybe not as effective as they could be... in my experience, spigot is also sometimes a little bit unstable compared to bukkit and makes more.
That's one of the reasons why I still use bukkit.^^

**Comment by EvilOlaf** [comment]
So. Got all the plugins and their configuration downloaded as well as the very same Spigot jar in 1.8.8. Removed the whole dynmap folder and let it recreate after restart. The fullrender of a new world (I did not download the existing world; that would take a long time) were flawless.
So it seems there is an incompatibility in the configs generated probably from 2.0 a while ago and 2.2 in combination with 1.8.7 and 1.8.8 which makes absolutely no sense....


Maybe I try to remove the whole config on the live system this weekend...

**Comment by Psy-Virus** [comment]
whoeeeey, klingt nach Spaß :tada: ^^

**Comment by EvilOlaf** [comment]
Absolut -.-

**Comment by EvilOlaf** [comment]
Seems like the problem has been solved by itself...not sure, just updated to a newer build of Spigot bug kind a unlikely to say that this caused the issue....Guess we will never find out.

So "fixed" for now.

**Comment by Psy-Virus** [comment]
:+1:
