### ISSUE TITLE
[Bug] Blocks from Galacticraft are not rendered

### ISSUE THREAD

**Issue by ExDomino** [webbukkit/dynmap#1820]
As I told on #1341, the blocks from Galacticraft are not rendered, but as you said it's already implemented, I consider that as a bug. I'm using the latest stable version of Dynmap for 1.7.10 (the 2.1) and the latest stable version of Galacticraft. Thanks you for advance!

**Comment by mikeprimm** [comment]
Support is version specific, and issue 1341 was opened in 2013 and resolved back in early 2014, so the corresponding support was for 1.6.x - appending to a mortibund and previously completed issues is a sure way to not get any attention.

I'll look at adding support for 1.7.10 - hopefully, basic support (for landscape blocks) should be pretty quick.

**Comment by draknyte1** [comment]
Can you still like into this mike?

**Comment by Psy-Virus** [comment]
Since Dynmap has the mod scraper and the block scanner, you should at least get partial support. If this is not the case, maybe you want to ask the guys over at Galacticraft, if they would like to implement support for Dynmap.

If Dynmap would support every mod or only even the 100 most downloaded, it would cost an extreme amount of time to keep up with the support.

Closing this because of old age and unsupported Version.
