### ISSUE TITLE
Suggestion: Enable a fixed zoom level

### ISSUE THREAD

**Issue by Taybosquee** [webbukkit/dynmap#1830]
I've been looking over the internet and pages linked from the Dynmap forum page, but if there is a way to do this I have not found it. I'm trying to make it so players can /not/ zoom in (or out) at all so the map would always be at the same zoom level. If there is a way to do this, I'd be great full if someone could explain how. If it's not possible, would adding it as a per-world/template setting be possible?

**Comment by mikeprimm** [comment]
Can't quite be done exactly as requested right now - the closest you can get is to:
1) Use a perspective with scale = 1 (the 'vlowres' perspectives are 2, so it'd need to be custom)
2) Make sure the world does not have 'extrazoomout' set above 0
3) Make sure the map has 'mapzoomin' set to 0

I'll look at an option to make the 'mapzoomout' (which is a function of scale - specifically the log(2) of the scale : 1 for 2, 2 for 4, 3 for 8, etc) settable (so that it can be zero).

**Comment by Taybosquee** [comment]
Alright. Thank you for your time. :)

**Comment by mikeprimm** [comment]
OK - just coded it, and should work as requested.  To get what you need, you can do the following with the /dmap command:
1) Set the world's extrazoomout to zero:   /dmap worldset <world> extrazoomout:0
2) Set the map's mapzoomout and mapzoomin to zero:  /dmap mapset <world>:<map> mapzoomout:0 mapzoomin:0
Build is running right now - should be ready by the time you read this
