### ISSUE TITLE
[SUGGESTION] Quick render

### ISSUE THREAD

**Issue by Flenix** [webbukkit/dynmap#1858]
Hey, just a suggestion for a feature I'd find very useful.

It'd be good if we could do something like a full render, except it skips tiles which already exist. It'd be great for things like worlds expanded via mod/plugin generators, or maybe smaller servers which don't have live updating to do quicker updates.

It's a feature I've wanted to use many times in the past so figured I may as well suggest it :)

Also, while I'm suggesting stuff, a render-per-zoom-level would be quite useful. I'm test generating massive maps right now and I'm using extra zoom of 6, and it looks like a single tile covers about 2 square kilometers of map area, meaning I could get a general overview of it all in a matter of a couple of minutes if I could just render the most zoomed out level.

**Comment by Psy-Virus** [comment]
The first thing can be achieved by using the `dynmap updaterender WORLD X Z` command.

The second would be possible by simply changing the config for the default world to zoom level 6 and change it to a more detailed zoom level after you're happy with the generated world.

I mark this as resolved because the this workaround is quite easy to handle.

If you still think this needs attention, please head over to the new Dynmap community support forum ( https://forums.dynmap.us/ ), were we can discuss this.
