### ISSUE TITLE
the map render speed is too slow

### ISSUE THREAD

**Issue by blackfoxsar** [webbukkit/dynmap#1920]
hi ,i'm a mc server op ,and i use the dynmap to make a map 

but the render speed is too slow,and my game map is VERY HUGE.(coordinate form -3216,-5784 to 9224,6664 and have 5 worlds)

(i believe my server hardware is very good: E5-1650 (no HT)/16G DDR3 ECC x2/Intel 750 PCI-E SSD 1.2TB)

so i want speedup the render speed ,can you help me?

**Comment by mooinglemur** [comment]
The initial full render of a map will take some time.  With a map that size, you could be talking about a million or millions of map tiles stored, depending on whether you have hires textures.  I have a larger map that took almost a week to fullrender.  However, once the render was complete, the map could easily keep up with changes.

If you want to decrease the render time, you can increase parallelrendercnt as high as the number of cores on your system, and/or tweak the shaders and zoom levels.  Otherwise, this is a large task that will consume quite a bit of CPU time to finish.

This is not a bug :)
