### ISSUE TITLE
Render triggers

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#1925]
Do I need to add  # to enable it, or disable it? Usually it's disable, but this seems the other way around?

render-triggers:
  #- playermove
  #- playerjoin
- blockplaced
- blockbreak
- leavesdecay
- blockburn
- chunkgenerated
- blockformed
- blockfaded
- blockspread
- pistonmoved
- explosion
- blockfromto
- blockphysics
- structuregrow
- blockgrow
- blockredstone

**Comment by SimonOrJ** [comment]
The plugin's configuration.txt file is mostly written in the way .yml files are written.  I'm not sure why the default extension isn't .yml yet since that'll save my eye by having the file color coded.

In .yml files, adding "#" will change the line after that to comment, and plugins or anything that reads .yml will skip whatever's written after it.  So,** to enable it,** you have to **remove the "#"** and keep the dash (-).  If you want **to disable it,** you can either **add the "#"** before the dash or just get rid of the line (getting rid of the line may cause visual confusion in case you want to re-enable something).

**Comment by Sikatsu** [comment]
Thanks for the explanation! I also wondered why it's still not .yml. Anyways, do you maybe know what will be the best ''Render-triggers'' list performance wise?

**Comment by SimonOrJ** [comment]
I don't know if there is a "best" render triggers list.  You can comment or uncomment any trigger based on what your needs are.  For a full vanilla server, the current list looks okay.  If, for example, your server disabled explosion damage, then you can comment out "explosion".  If your server does has fire tick turned off, comment out blockburn.  If your map does not allow block modification, comment out blockplaced, blockbreak, leavesdecay, blockphysics, etc.  It all depends on your needs and logic.

**Comment by FedUpWith-Tech** [comment]
@Sikatsu  you should close this issue 😉
