### ISSUE TITLE
dynmap purgeworld world crashes my server

### ISSUE THREAD

**Issue by Rocologo** [webbukkit/dynmap#1964]
Thank you for a wonderful plugin!

I have found a bug which makes my server crash each time.

I have recently deleted my world "survival" and needed for this reason to purge the dynmap survival maps to, so I ran "dynmap purgeworld survival" and after awhile the server crashes - each time i try.

I actually know what the problem is, but I don't know how to solve it. The problem is that my dynmap mysql database has become to big so when you/i try to select all tiles from a world or a map you get very long reponse times, so after waiting a minute minecraft/multicraft think that the server has crashed, and restart the server hard.

[http://pastebin.com/q9p8AXUE](url)

I'm running SpigotMC 1.10 + Dynmap 2.3 by the way, but it was also a problem in the previous versions of Spigot+dynmap

**Comment by Dominic001** [comment]
Hi

I have experienced this by myself, and as far I can say the problem is not dynmap. It just happens because your mysql is too slow in handling the request and doesent handle any other requests during this time. Make sure your mysql server is properly configured. Following some tuning guides has helped me a lot to reduce this kind of crash.
