### ISSUE TITLE
Dynmap periodically deleting

### ISSUE THREAD

**Issue by VaktimusPrime** [webbukkit/dynmap#2042]
My Dynmap will compete a full render of the world, and then perhaps a day after the render completes the map will reset and the whole map will be blank and I have to run it again.

This is a bit tedious as it takes a lot of resources to run the full render so often and it laps the server for my players. Is there something I should be doing at the end of the full render so that the map data is saved? 

Not sure where to start on this issue so if i need to provide any other information for a diagnosis I will happily do so. 

Thanks

**Comment by wioxjk** [comment]
How do you store the dynmap? can you try store it with mysql?

**Comment by bud-lwos** [comment]
This has happened to me also. I posted about it here: https://github.com/webbukkit/dynmap/issues/2039

After my re-render, it has been fine -- has not deleted the tiles again. 

I am not using mysql to store the maps.

**Comment by WonderDave** [comment]
Where is your server being hosted? I only ask because I used to have a server hosted on MCProHosting, where they state that Dynmap needs to be set to its lowest quality (to avoid violating their AUP). My map files vanished on a couple of occasions, and I assumed that MCProHosting had deleted them. That may not be what happened there or what is happening here, but I thought I'd mention it.

**Comment by bud-lwos** [comment]
I'm hosted by Bisect. I don't think they deleted the files.

**Comment by TonyGravagno** [comment]
FYI: Another MCProHosting client here with files missing over time. Current usage is 160000 files in >2GB of disk. I'm thinking they do an autopurge without notice, just glad they selected the right folder. I'm migrating to dynmap data in MySQL.
