### ISSUE TITLE
HTTPS Option

### ISSUE THREAD

**Issue by Lantianer** [webbukkit/dynmap#2048]
Hello,

with most of the new browser versions you can't see / open the live map integrated in an iframe on a https-website. Can you add an option or create a wiki description to setup DynMap with https?

Kind regards

**Comment by wioxjk** [comment]
dynmap itself does not support https atm, but you can quite easy create an reverseproxy and achieve that.

**Comment by Lantianer** [comment]
Thats why i opened this issue ;) A small documentation for newbies or a function in future versions.

**Comment by wioxjk** [comment]
Are you familiar with apache and Linux? 
Maybee this can help you, if you know apache before, this should be quite easy:
http://serverfault.com/questions/799012/dynmap-throu-mod-proxy-on-a-external-webserver

**Comment by Lantianer** [comment]
We use Nginx, do you have something similiar for that kind of webserver?

**Comment by wioxjk** [comment]
I do not, sorry! 
Prefer apache in all cases :)

**Comment by Twml1500** [comment]
I didnt see your post i just posted about the same issue, 
lack of https. but for me i cant use dynmap without it the way my domain is configured for security.

My issue report:
https://github.com/webbukkit/dynmap/issues/2049

**Comment by jwshields** [comment]
If you want https support, you're better off using a proper server (like nginx) and serving thing that way. Jetty is not meant for real high performance web content.

**Comment by jwshields** [comment]
The Dynmap jetty instance is also not super configurable other than what port it's on really. It's not meant for doing much of anything other than the default setup.

**Comment by Twml1500** [comment]
I cant use my nginx server to display the dynmap content that would mean iframing it into a page, making the browser throw a mixed content error. and not load the content. you cant iframe http content in a https page anymore without manually enabling it on the client every time, it throws a security warning. its to prevent an attacker from modifying that http page inside of the https page. 

would be nice to see https added directly to dynmap

**Comment by jwshields** [comment]
iframes are a security exploit and it's not expected that it be done.  You either use your httpd as a proxy/forwarder to talk to Jetty, or you disable Jetty and serve the files natively from your httpd.

I used to serve my files using nginx as a reverse proxy to Jetty over https and didn't run into issues.

**Comment by jwshields** [comment]
Jetty is not made to be a fully-fledged webserver. That's why there are wiki pages on here describing how to forward traffic to jetty or avoid it altogether. Doing an iframe is a backward way of serving content and opens yourself up to other issues.

I see no reason to make Jetty in this instance support https. How will it generate certs, automatic/manual? Not every box has openssl/libressl. Would you prepackage the certs? That would be easily exploitable. You'd also need to edit the config for dynmap to allow for more options (what other ports to listen on, what certs to actually use)- what about version upgrades? how will that affect the config between different versions who have/don't have that? What about the idea of even having a cert, if it's self signed your browser will throw an error anyway. And with things like let's encrypt it's easy enough to spin up an instance of nginx and get a legit cert that won't error.
