### ISSUE TITLE
Dynmap not rendering when people walk around the map

### ISSUE THREAD

**Issue by IdanHo** [webbukkit/dynmap#2086]
my render triggers are:
render-triggers:
  - blockupdate
  #- blockupdate-with-id
  #- lightingupdate
  - chunkpopulate
  - chunkgenerate
  #- none

but still, when people walk around, it doesnt render.

(its 1.7.10)

**Comment by rautamiekka** [comment]
Read the list of triggers again, you're missing the obvious ...

**Comment by DrPiggy** [comment]
@rautamiekka huh?

**Comment by SimonOrJ** [comment]
Render-triggers list is spelling-sensitive.  Check your list against [the default configuration list](https://github.com/webbukkit/dynmap/blob/master/src/main/resources/configuration.txt#L286).  More information [here](https://github.com/webbukkit/dynmap/wiki/Base-Plugin-Settings).

**Comment by DrPiggy** [comment]
@SimonOrJ isnt that list for bukkit? im using forge.

**Comment by SimonOrJ** [comment]
I'm sorry, but you did not specify you were using Forge, so I could only assume you were using the Bukkit version.  Please add that somewhere in your issue next time.

Does your server's tps drop under 18?  Based on [this part of the config](https://github.com/webbukkit/DynmapForge/blob/master/src/main/resources/configuration.txt#L353), the default is don't render anything when server lags under 18 tps.

**Comment by DrPiggy** [comment]
@simonorj i have perfect 20 tps

**Comment by floomat** [comment]
i have the exactly same issue and changing something in the trigger list doesn't change anything. expect when you change blockupdate or remove it. Thats when the Dynmap stops doing it's job, I assume there is a huge bug in the forge version which causes the triggers to fail at all, expect blockupdate. You can check this by looking at the "dynmap triggerstats", it only shows blockchange which i assume is blockupdate. I can remember as i had a bukkit server a few years ago and the list was huge on "dynmap triggerstats".

Please fix this...

**Comment by smmmadden** [comment]
@floomat If you're having issues with Forge, make sure you're using the [Forge version](https://minecraft.curseforge.com/projects/dynmapforge/files) of Dynmap to match whatever server/release you are on.

**Comment by floomat** [comment]
Im using Spongeforge 1.11.2-2282-7.0.0-BETA-2356 with Forge 2282 and dynmap 2.5 alpha 1.

**Comment by smmmadden** [comment]
That's most likely the problem. I don't believe (@mikeprimm can say otherwise), the 2.5 version is going to work for 1.11.2 Spongeforge.  There is a 2.4 version for 1.11.2 which is most likely what you need to use.  I don't use Sponge or Forge, so can't speak to the compatibility of this plugin.  I do know that other plugins have had to be rebuilt to get them working with Forge.  I don't know if that's the case here.

**Comment by floomat** [comment]
@smmmadden did you read my reply/edit? it doesn't change anything if i use 2.4, it's the same behavior with both versions. i tried standard config, i tried modified config, i tried everything. this is clearly a bug with the forge version of dynmap.

**Comment by mikeprimm** [comment]
You definitely want to be sure to have the Forge version be a match (there is still a 1.7.10 build, so you are probably good there).  The 'walking around' render thing is a different question: are they walking around and causing new chunks to generate, or walking around to visit existing chunks?  The old 'playermove' trigger that the Bukkit version supports was never implemented on Forge because the performance problems it caused far exceeded any value of the feature - players moving around caused absurd amounts of rerendering of the chunks in the 10 chunk radius around them (independent of whether the chunks needed refreshing, nor whether they were already rendered) - never met a user that was happy with the outcome, so it was dropped.  I could be considered, but it'd need to be something on the line of 'only do the render if the tile doesn't already exist' - the original feature was absolutely as 'be careful what you ask for....' feature.

**Comment by mikeprimm** [comment]
As always, the latest 'bleeding edge' builds (and older release builds) can be found here: http://www.dynmap.us/builds/DynmapForge/

**Comment by floomat** [comment]
@mikeprimm wow, never thought i would get an answer directly from you.
First of all: Huge THANKS for the great work on this admirable plugin.

The problem especially affects rendering if new chunks are generated, you can check this by setting up a simply 1.11.2 spongeforge server and walk around and check "dynmap triggerstats" normally there should be a list with all triggers that were fired but it only shows blockchange (i.e. blockupdate).
You also will recognize that the blockchange is very high, this is due a change in spongeforge with the async lighting thread which causes a massive amount of blockchange triggers and actually this "fixed" the missing rendering of new chunks, but not as good as it just would work as intended, it still leaves some unrendered tiles and i have to manually re-render by dynmap radiusrender or fullrender.

I see there is a new version out, i will check it as fast as possible. Again, thank you for the great work you did for us.

best regards
Flo

**Comment by mikeprimm** [comment]
Cool - I'll give it a look.  Please confirm the following:

- Is this behavior distinct to when SpongForge is present?   (I want SpongForge to work - just need to know if it is impacting my implementation: it would not be the first time)
- BlockChange (notifyBlockUpdate) usually is different than lighting (notifyLightSet) - I'd need to understand more about what SpongeForge is doing, since that sort of behavior change would be bad for a lot more than just Dynmap (block change loggers would kind of lose their minds, and protection mods would take a lot of load).  The problem with the behavior change (load aside) is that there probably isn't a good way for me to tell the difference between real block change events, and SpongeForge lighting generated noise.
