### ISSUE TITLE
[BUG] Rending black terrain?!

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#2090]
After reading comments that the custom texture pack ive used for 4 years Dokucraft light to render my map breaks 1.11 dynmap as there is a shulker texture it does not like, it throws errors in console, so I edited the pack by removing the skulkers and reloaded the plugin in-game and did a render, and the errors were gone! Until I checked the map and its rendered some weird black box!
http://i.imgur.com/Ur821tQ.png
https://map.piratemc.com

So I thought I would move back my 1.8 DokuCraft.zip as I knew that worked, but no! It did the same thing!
What the hell is going on with DokuCraft and Dynmap on 1.11?

**Comment by MamylaPuce** [comment]
Hello FrozenBeard,
i had the same issue, this solve me the problem too ^^

(sorry for bad english, i'm french)
I have a question because i have an issue that i can't resolve, i visit your Dynmap (wonderfull job ^^) and i can see that You succeeded to protect chat message with login and registration and that's my problem : for my Dynmap, i made well configurations in config.txt but when i put the registration code and clic on Register => NOTHING HAPPEN !

Me and all of my friends have the same issue, impossible to register for the chat, nothing happen while I obtained well the code for each of them. I search again and again, i have tried everything but always the same issue...

Did you met the same problem ?

I am on Dynmap-2.4-forge-1.11.2.jar and MC 1.11.2

**Comment by SimonOrJ** [comment]
Hey @FrozenBeard, does the issue still exist? Your dynmap shows that your map is rendering properly now...

**Comment by FrozenBeard** [comment]
@SimonOrJ Nope! I solved it, but sadly for anyone that finds this ticket through a google search, I cant remember how I did it! If I were to guess, It was getting a working pack and restarting the server fully, the in-game reload does not /dynmap reload the pack properly.

@MamylaPuce I think there was a registering issue when you use PHP version 7? I remember seeing something like that in a ticket once. What version of PHP do you have?

**Comment by MamylaPuce** [comment]
I don't really know what version of php we have on the server because the server is hosted with "Boxtoplay" site : https://www.boxtoplay.com/fr/

But i think you could be right, one of my friend thinks that it also could result from of php problem and we are going to make some searches and tests. I don't know how can i find the php version except by asking the administrators maybe...

**Comment by smmmadden** [comment]
or post a question on their support forum page. But they would know what they're using.

**Comment by SimonOrJ** [comment]
Dynmap reload is pretty broken D:

The PHP problem should be fixed if you're using the latest snapshot of dynmap as Mikeprimm accepted my pull request to fix the PHP7 compatibility issue.  Also... let's keep the chat register problems in issue #2095.
