### ISSUE TITLE
Updaterate can't go less than 1000

### ISSUE THREAD

**Issue by tridaak** [webbukkit/dynmap#2104]
Using latest forge version for 1.10.2, messing with the settings and realized, when setting the update rate in the configuration.txt to anything less than 1000 (1 second) it won't update player positions any faster than a second.

**Comment by SimonOrJ** [comment]
I would not recommend that.  Dynmap webpage gets update through HTTP requests, and increasing the update interval will give the web server more stress, especially when a lot of people are viewing the dynmap, due to the relatively huge  HTTP header headway.

If web side of dynmap was coded to update using WebSocket, then the update rate will not be necessary (as WebSocket is bi-directional and lightweight).  Until we get there, it's best to keep update rate longer.

**Comment by tridaak** [comment]
Does dynmap use HTTP2 by default? Wouldn't that reduce the overhead, not sure if it'd be enough to have an updaterate of 0.5 seconds or so.

As for people viewing dynmap. Not a whole lot of users are on dynmap at a time, if it becomes a problem, server owners have access to web files; by editing them and changing stuff, they can limit number of users per IP or per session using the map, edit the js variable if too many users are on at the same time to update more slowly and even prevent users from showing up and updating.

**Comment by SimonOrJ** [comment]
The dynmap page uses whatever HTTP the webserver uses to update.  You have to remember that the way it updates hasn't been updated since 2013-ish.  At this point, I think it's better to redo the web with latest version of leaflet and by utilizing WebSocket.  It's just the matter of who's going to pick up on redoing the web side of the project.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
