### ISSUE TITLE
Dynmap 2.5 Rendering black blocks for some textures.

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#2110]
Looks like smooth stone is rendering black blocks when I use 2.5 with my Dokucraft texture pack, And I can't update it as this Bug isn't fixed with the code around Shulker boxes.
https://map.piratemc.com/

**Comment by MrSpock78** [comment]
Seems Chiseled_brick and mossy_brick are not even rendering(black).
I use 2.5 and hires-template on latest Paper 1.11.2. 
The plains-grass texture also having a darker green like in taiga biome since 2.5.
Ingame:
![ingame](https://user-images.githubusercontent.com/28217121/27277058-4ecc0ede-54dd-11e7-8846-dcf517990bff.jpg)
Dynmap:
![dynmap](https://user-images.githubusercontent.com/28217121/27277061-5044ae56-54dd-11e7-9140-7a20cb401b50.JPG)

**Comment by FrozenBeard** [comment]
To add to this its not rendering  smooth stone, dirt, grass, wool and gravel.

**Comment by mikeprimm** [comment]
Just patched CTM handling in latest dev builds for 2.6 - give these a try

**Comment by MrSpock78** [comment]
Thx a lot. Seems all blocks are now rendered correctly.
But there is still a small issue with the biom-color of plains:
The plains-grass texture also having a darker green like in a taiga biome since 2.5.
![j31ykdc](https://user-images.githubusercontent.com/28217121/28017500-d5677576-6579-11e7-81b6-163ef9b96449.jpg)

**Comment by FrozenBeard** [comment]
@mikeprimm Yes! I can now load a 1.11 Dokucraft texture pack and its rendering http://map.piratemc.com/
Theres a few black blocks still as its not fully rendered yet. but look from spawn outwards to see how its rendering.
