### ISSUE TITLE
speed of the web server

### ISSUE THREAD

**Issue by FrankHeijden** [webbukkit/dynmap#2148]
Hey,

is there a way to improve the speed of the tiles loading at the online map? currently its very slow. I tried decreasing `updaterate` in the config, but it didn't work.

Frank

**Comment by smmmadden** [comment]
I don't think this is a dynmap issue to resolve.  Have you contact your web hosting service to see if there is an issue there?  Without knowing how you configured dynmap, your hosting service for Minecraft or knowing which part of dynmap you see slowness it would be a guessing game.  You also haven't stated what O/S, Server & Version of Minecraft, Version of Dynmap and how slow is very slow. :-)

**Comment by FrankHeijden** [comment]
Ubuntu 17.04; Apache latest stable release; server mc 1.12.2 (git-Spigot-5695bca-53fccdf)

You can see the slowness at https://maps.aquacraft.eu/survival

**Comment by smmmadden** [comment]
Frank - I see the map loading a chunk at a time which is how mine loads.  I am curious though as to the size of the map and the resolution you choose.  The default is "hires" but I've changed my worlds to low_boost_hi due to the size of my worlds.  This one is our [largest world](http://www.takemetominecraft.com:8120/) which is 1/3 of the maximum world size of 10,000,000.  It paints a little slow, but still loads faster than what yours did.

Assuming this is hosted elsewhere, have you run tracert to see how many hops it takes to hit that server and the speed?  Here are the result for me (USA / Eastern Timezone) and there are problems with packet drops/loss.  So I'd say change your map setting and also check with the aqaucraft.eu to see if they have servers down.
![image](https://user-images.githubusercontent.com/10309346/32195638-3cc2dc3e-bd94-11e7-8d14-ae3063a8b520.png)

**Comment by jwshields** [comment]
Your dynmap config seems to be a mess, tbqh.
Are you using Apache to proxy requests to the Jetty webserver or are you using the JSON file for external webservers? Because you have _both_ settings enabled, to use Jetty, and create a JSON update file. 

If you're using Apache to proxy requests to Jetty, get that resolved first off, extra hops/proxying web requests introduces latency - best option is to disable jetty and use a dedicated web server by itself.
If you're not proxying requests, fix your config to disable Jetty and the internal file updates.

That aside, this blocking/slowness seems to be coming from your database.
Watching in the Chrome request log I see requests for the html/content taking miliseconds, which is acceptable/good - That means that the web server, apache, itself is _seemingly_ in good health.

But once we get into requests for `MySQL_Tiles.php` - the requests start getting into the range of taking multiple seconds. 
Please see the screenshots below....

How is your MySQL DB set up? Do you have any customizations to the config? Is this hosted in the cloud/locally? Is the DB itself hosted in RAM, spinning disk, SSD? Are other applications/tools/users using this DB as well? (Normally MySQL handles concurrency well, but it's still a good idea to handle for high utilization)

In all, this is **_not_** a dynmap issue. 




![20171031 - aquacraft eu - initial requests](https://user-images.githubusercontent.com/7400556/32242646-90292a26-be30-11e7-9b02-081f9395e2ee.PNG)
![20171031 - aquacraft eu dynmap slow](https://user-images.githubusercontent.com/7400556/32242647-903c68c0-be30-11e7-863a-ea8b744b2c50.PNG)

**Comment by jwshields** [comment]
If you no longer need assistance, please close this issue, or provide an update with regards to the help that has been given
