### ISSUE TITLE
Issues with web service

### ISSUE THREAD

**Issue by JackInTheBootyCrack** [webbukkit/dynmap#2152]
I cannot seem to launch up the web server to view the map... I did everything that the instructions told me and rendered the map as well as reloaded the server and I try to goto the website and it fails. Can I get a walk through on how to do it? I know this sounds like a newbie thing to say, but I am completely and utterly lost here. Any help would be appreciated. (The error I receive in my browser is ERR_CONNECTION_TIMED_OUT) and my internet is working so it has to be on the server side correct?

**Comment by jwshields** [comment]
You're using the internal web server? Or do you have another httpd (nginx, apache, etc)?

What does your config look like? When starting bukkit, does the output log show output of dynmap?
Assuming you're running the internal/default, it should show something like this: 
```
[13:06:49 INFO]: [dynmap] Web server started on address 0.0.0.0:8123
```

Also what url are attempting to access this with? Is your server behind a NAT? Are you hitting the external IP? Internal IP? localhost? Check your port forwards if you're behind a NAT, check your OSs firewall is/isn't blocking the port.

Could you post your config here, as well as info about your OS, basic network details (is this a dedicated computer, behind a router, same computer you're playing on, etc?)

**Comment by JackInTheBootyCrack** [comment]
I am using the internal web server I believe. Also I am using the spigot version.  I am not sure what the rest of what you said was. I am sorry. I am typing the IP like it says (https://0.0.0.0:8123) and it gives me the error my issue probably results from me being very dumb and missing something basic, but here is my config.
[configuration.txt](https://github.com/webbukkit/dynmap/files/1443586/configuration.txt)

**Comment by jwshields** [comment]
Alright; I see!
Do you know the IP address of the computer the spigot server is running on?
Try using that with :8123, and it should be **http**, not https.
Example, my server is `192.168.1.153`, so i'd hit `http://192.168.1.153:8123`
But because I'm behind a router, if I wanted to have other people get on it, i'd need to forward the port (in this case for the map, it is 8123, but also the minecraft server uses its own port 25565)

**Comment by jwshields** [comment]
As a note, the 0.0.0.0 is a placeholder and means "all networks" - so, for example if your computer was on multiple networks and had multiple IPs, it'd show up on all of them.
Mind, I'm assuming you're serving this from home rather than a dedicated server or something; but...
If you don't know how to port forward, google "how to port forward" and include your ISP (comcast, qwest, etc), or the model of your router
Then you can go to a site like `whatsmyip.org` and it'll tell you the external IP address, that way, once the port is open, others can visit the server.

**Comment by JackInTheBootyCrack** [comment]
I have just done what you said to do, and used http instead of https and i'm getting the same issue. Also I am using a host for this. I am quite lost here...

**Comment by JackInTheBootyCrack** [comment]
keep in mind I am using my servers actual IP not 0.0.0.0

**Comment by JackInTheBootyCrack** [comment]
If I have a port how do I format the address?

**Comment by jwshields** [comment]
Like this: 
`http://yourip:8123`
`http://192.168.1.50:8123`

**Comment by Too-DAMN-Much** [comment]
i am having the same issue with the forge version of dynmap #2217 
ports are forwarded correctly, both internal and external IPs are functional and visible except for dynmap's port.

i have double checked my firewall configuration and everything is fine there, the ports are explicitly allowed with rules for both TCP as well as UDP both inbound and outbound rulesets for each.

at least for me personally, this is a dedicated server running mineos with minecraft 1.12.2 and version 2640 of forge.

i've not seen dynmap be functional at all in any way since 1.7.10, which is sad, this was a really useful mapping tool while it lasted.

**Comment by Too-DAMN-Much** [comment]
just in case it helps anyone else, if you're using a linux OS you'll need to edit the iptables (built in firewall) and allow the dynmap port, go find the relevant manpages to open and forward the relevant port you set for dynmap and see if that fixes the issue for you as well.

bit of a stupid thing to have missed, but i really had no clue a dedicated server hosting OS would have any kind of built in firewall.

**Comment by zrovihr** [comment]
Yeah I also got this problem.. it loads 0.0.0.0.. it probably messes with my port
