### ISSUE TITLE
perspective not changing

### ISSUE THREAD

**Issue by FlatoutDude** [webbukkit/dynmap#2174]
Hello, i've modified dynmap to face SE, but, the compass is still showing North, I'm currently using HighRes, but that doesn't really seem to do anything, i've tried fiddling with anything relating to that, but so far, there are no changes, no matter what i do, it's in the same perspective

**Comment by FlatoutDude** [comment]
here's the URL:
104.13.120.110:8123

**Comment by FlatoutDude** [comment]
bump

**Comment by Pisi-Deff** [comment]
From what I understand, this is expected behavior.
The perspective setting sets where the "viewer" is looking from.
E.g. if the "viewer" is looking from the southeast, then on the compass northeast is pointed "away" from the "viewer", upwards.

If you want to spin the map around, try setting the perspective to northwest.
