### ISSUE TITLE
[Feature Request] Update WebUI

### ISSUE THREAD

**Issue by simonjonnemeth** [webbukkit/dynmap#2216]
The current one is old and ugly and things are small on higher resolutions (not the maps obviously). Possibly due for a redesign? I made some changes to my own installation which are an improvement though they are not perfect. Call it a functional concept:

![2018-03-31 1](https://user-images.githubusercontent.com/1496797/38168230-9fe45f5a-353e-11e8-9cb5-ccd6a1d56cb4.png)

![2018-03-31 4](https://user-images.githubusercontent.com/1496797/38168232-aa387342-353e-11e8-8869-6a29a2af3437.png)

![2018-03-31 3](https://user-images.githubusercontent.com/1496797/38168247-0021ac1a-353f-11e8-9847-f136e087a09a.png)

[http://minessmap.lidosofbritain.co.uk/](http://minessmap.lidosofbritain.co.uk/)

**Comment by generrosity** [comment]
nice! what files in particular did you modify? Just one?

**Comment by generrosity** [comment]
I did a similar thing with the custom CSS file, making all the icons ~twice as big. I could be picky about it, but it works... And I can easily swap icons over for higher resolution ones.

**Comment by simonjonnemeth** [comment]
I did most of the work with Google Chrome's built in tools and changed the values in the respective style sheets manually.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

Additionally, there are two new webUI's that are community map-  [Material UI](https://github.com/SNDST00M/material-dynmap/tree/v0.4.3) and [LiveAtlas](https://www.spigotmc.org/resources/liveatlas-a-dynmap-frontend-for-the-modern-web.86939/)
