### ISSUE TITLE
Vines don't render correctly.

### ISSUE THREAD

**Issue by simonjonnemeth** [webbukkit/dynmap#2298]
Vines haven't rendered properly in any 1.13 compatible build. This is from today's build:
![aaaaa](https://user-images.githubusercontent.com/1496797/44597949-502a1380-a7c9-11e8-9eaa-737a97431a70.PNG)
![aaaaab](https://user-images.githubusercontent.com/1496797/44597955-54eec780-a7c9-11e8-9450-2f2aef24f271.PNG)

**Comment by smmmadden** [comment]
Looks similar on my server as well.  Kind of blury getting close to it on surface and flat.
This is from the map
![image](https://user-images.githubusercontent.com/10309346/44613729-20d5cf80-a7e6-11e8-961c-7a21caa0d3b4.png)
This is from in-game
![image](https://user-images.githubusercontent.com/10309346/44613731-24695680-a7e6-11e8-9255-3c937f3adee5.png)

**Comment by mikeprimm** [comment]
Fixed in v3.0-alpha-2

**Comment by simonjonnemeth** [comment]
Almost. Not perfect but way better. I'd rather 1.13 compatibility not be dropped just yet since most plugins haven't even caught up with 1.13 yet. You shouldn't be leaving things behind.

**Comment by mikeprimm** [comment]
Spigot is leaving 1.13 behind - no reason to support it if Spigot isn't....

**Comment by smmmadden** [comment]
I agree - as soon as SelectionVisualizer and WorldEdit are fixed, I'll be switching to 1.13.1 builds as well.

**Comment by simonjonnemeth** [comment]
Like I said. Barely anything supports Spigot 1.13 yet, let alone 1.13.1. You should wait for things to catch up.

**Comment by smmmadden** [comment]
actually not true - https://www.spigotmc.org/wiki/spigotmc-compatible-plugins-by-release/

**Comment by mikeprimm** [comment]
Anything that needs updating but hasn't been updated to support 1.13 yet is probably just going to skip 1.13 and support 1.13.1 (e.g. I can guarantee that there will never be a Forge 1.13, and probably no released Optifine 1.13 since there isn't one presently) - just about nobody specifically *adds* support for an obsolete minor release: they only maintain support already added (if even that).  It's just a poor use of time to develop, test, and support a minor point release that is already obsolete.  Most modders don't even bother continuing support for older major versions, once the new major version is at a production-usable level - Spigot lets you get away with it more, since the ABI has been relatively release-to-release stable, but the Spigot v1.13 release broke a lot of very long standing interfaces due to 1.13 having changed as much as it did internally.  

My long term support policy for Dynmap has been one of the more generous ones - I'm still building and enhancing code for both Bukkit/Spigot and for Forge for the last minor release for every major release since 1.8 (that is 1.8.9, 1.9.4, 1.10.2, 1.11.2, 1.12.2 and now 1.13.x).

**Comment by simonjonnemeth** [comment]
Optifine has had several pre-releases for 1.13. I'm using one. The current progress is around 80%. That's a small list smmmadden.

**Comment by smmmadden** [comment]
that list represents 300+ 1.13/1.13.1 resources updated just in the last 2 weeks. And based on past experience going from 1.7 to now, that's a huge improvement in turnaround especially since Mojang changed thousands of block id's.  Is it complete, heck no.  Is it current with what folks are telling me, yes and still being supported.  I do not and will not add resources that don't work for 1.12 or higher in one of the server types listed in sheets at the bottom of the spreadsheet.  Also if new ones come out or have not made it to this sheet, unless I'm asked to include it (assuming I miss it), then it wont be added either.

You always have a choice of what version you want or don't want to use, so even if everyone released 1.13.1 as the official/only one to support, you can choose to upgrade or not.  We all still have free will :-)

**Comment by smmmadden** [comment]
you are right about OptiFine that they have a 1.13 build, but it too is a beta version which may not go GA.  It's entirely up to owners if they want to support version 1.13+ or just 1.13.1 as they choose.
OptiFine 1.13_HD_U_E3_beta2
 - early preview, not all functions are tested
 - not working: anisotropic filtering, antialiasing
 - partially working: shaders
 - fixed connected glass panes (#1661)
 - fixed cloud height
 - fixed crash with block slab using wrong block state (#1717)
 - fixed Dynamic Lights to correctly reset on enable/disable (#1680)
 - fixed water colormap
 - fixed fluid animations with Smart Animations
 - fixed rendering of players with non-latin usernames (#1637)
 - fixed crash with TIS-3D Rift (#1677)
 - fixed Video Settings to save on ESC
 - fixed custom lightmap channels
 - added Fullscreen Resolution
 - fixed crash in Statistics
 - fixed Fast Math accuracy
 - added shader uniform "fogDensity"
 - fixed fog options
 - fixed FXAA flipping screen vertically
 - updated to 1.13
(27.08.2018)

**Comment by mikeprimm** [comment]
It's already been announced that there will not be a Forge for 1.13 - only for 1.13.1 plus.  The fact that OptiFine started work during 1.13 doesn't change the fact that they haven't released anything for 1.13 as a supported build, and are unlikely to do so (look at their download list, and note all the gaps in their release list vs MC patch versions).  It's a pointless discussion - like most modders, I've got higher priorities than supporting unsupported releases, so 1.13.0 support is going in the trash heap shortly.

**Comment by smmmadden** [comment]
couldn't agree more.  I've already stopped using 1.13 builds and only testing 1.13.1 now that a couple of my critical resources have been updated.  Forward and onward they say....
