### ISSUE TITLE
Vines are still not rendered 100% correctly.

### ISSUE THREAD

**Issue by simonjonnemeth** [webbukkit/dynmap#2321]
The undersides of the vines are still a block too low. They shouldn't even be rendered at all in most cases. This was previously marked as fixed but it clearly isn't. This is of the latest snapshot (3rd September).
![capture](https://user-images.githubusercontent.com/1496797/45030935-6182e380-b045-11e8-8d7d-973ae50dbed3.PNG)

**Comment by mikeprimm** [comment]
Not seeing a problem here - the underside rendering is consistent with the fact that you've somehow gotten underside vines on an inverted stair (which is only half width on the bottom) - I'm assuming worldedit for that.

For test, here's what I get:

![image](https://user-images.githubusercontent.com/654487/45040875-9b93bb80-b02c-11e8-8d38-28f0d7f328fe.png)

For following from game:
![image](https://user-images.githubusercontent.com/654487/45041485-085b8580-b02e-11e8-9490-9e9d2a44cccd.png)

What I see on your image is a half block offset due to the bottom of the block being an inverted stair. - can I get an in game shot to compare with the render?

**Comment by simonjonnemeth** [comment]
You're right! I have no idea how that happened. I think it may have happened in the conversion to 1.13. I don't know how I didn't notice actually. Sorted.
![dyn](https://user-images.githubusercontent.com/1496797/45046073-f77e3480-b06c-11e8-94da-92d04c47ffea.png)
