### ISSUE TITLE
Dynmap Spigot Server crashing

### ISSUE THREAD

**Issue by vic197** [webbukkit/dynmap#2324]
I have narrowed down my random crashing to dynmap. It has been going on since I added it. I am not rendering or filling anything, just having the plugin on makes the server crash.  First the server stops responding then this is what the server spits out

https://pastebin.com/0RSrhCh0

**Comment by smmmadden** [comment]
Hard to tell from what you provided as that's just the thread dump and not what happened before it. 
 It does appear like you have an older version of Dynmap on your server. 
dynmap v2.6-beta-1-Dev201807082003
There are other versions available more recent than this one that I would suggest using.  If you have the log prior to the thread dump, that'll provide more details on what might have caused the crash.  For example, if the server starts up and then immediately crashes, then provide the whole log, not just the last part.

**Comment by vic197** [comment]
Just added versions 3.0 alpha 3 to see if anything happens. I've read the log completely and there is nothing to indicate an issue, just how a normal server log looks. If anything happens again after putting in the new version I will add it to the thread

**Comment by smmmadden** [comment]
okay, but didn't you state that the server crashed after putting in the 2.6 version?  Are you saying now that you have version 3 the server no longer crashed and **all plugins** (including Dynmap) loaded **with no warnings or errors at all.**  My point being is that what looks normal to you for a startup does not necessarily there isn't another problem that may be causing drop issues with this one.  We don't have that visibility so providing a full startup log and the point where the error occurs will give us 95% of the data we need to troubleshoot it.

Just to also iterate that putting in the dynmap into the plugins folder doesn't automatically mean it will work because there are required configuration.txt file changes and permissions to be added to make it work properly.  If you have WorldBorder installed, then a /wb fill once the border is set should be run.

**Comment by mikeprimm** [comment]
@vic197 Nothing in your log to suggest Dynmap as an involved party.  From looks of it, I see multiple threads blocked trying to do file I/O, which might suggest a file system problem (e.g. if you were running on a network share or had load/performance issues with the drive).  The exception is on the server thread, and dynmap isn't part of the stack shown - the fact that other threads are present with dynmap's name doesn't imply anything other than that dynmap has a thread pool.  If you have any more information on whether 3.0-alpha-3 works well for you, I'd be interested in hearing!

**Comment by vic197** [comment]
Update: So with the new version, still prevelant. What happens is the server will freeze and so will the computer. I have 7gb of ram allocated to it. Here is a log from start to finish, for some reason it took 20 minutes for the server to say "Done." 

https://pastebin.com/X1tNHT1s

**Comment by smmmadden** [comment]
I have to concur with Mike - the logs show a warning with AnimatedFrames (trivial), but then ClearLag was the last entry before the thread dump and server crash.  I would investigate ClearLag first and work backwards since the thread dump is a result of one of the last actions taken that wasn't handled well.

I did notice one thing though during the initialization of Dynmap you have playermove enabled in the configuration.txt file for when to update renders which comes at a price.
[07:28:00] [Server thread/WARN]: [dynmap] playermove trigger enabled - this trigger can cause excessive tile updating: use with caution
[07:28:00] [Server thread/INFO]: [dynmap] Enabled

I don't believe this is the root cause as something else is clearly wrong, but what happens if you use the default OOTB settings below.  Again, Dynmap didn't make it to the point of rendering when the thread dump happened. 
render-triggers:
  #- playermove
  #- playerjoin
  - blockplaced
  - blockbreak
  - leavesdecay
  - blockburn
  - chunkgenerated
  - blockformed
  - blockfaded
  - blockspread
  - pistonmoved
  - explosion
  #- blockfromto
  #- blockphysics
  - structuregrow
  - blockgrow
  #- blockredstone

**Comment by mikeprimm** [comment]
ah - playermove is really a bad one (been there forever, and off by default, but it is a really expensive one to have on, since players moving in chunks that otherwise don't get changed will be marked for rerender, which is really excessive).

**Comment by vic197** [comment]
Alright. Will fix the playermove in config. But I am not sure how that is a cause because it will crash even when the server is empty for days. Once again I removed the plugin and the crashing seized. But I will troubleshoot dynmap by having that plugin by itself and adding each plugin one by one, might be conflicting or something like that. Will see clearlag, but I can see how animated frames could be an issue. I will update you guys as soon as I get to it

**Comment by smmmadden** [comment]
sounds good @vic197  - I don't think the playermove or Dynmap for that matter is causing the crash.  Animated Frames might be?? But ClearLag was the last entry before thread dumping.  I can tell you for sure that one of the plugins I use will shut the server down if it has a severe exception (like when we moved to 1.13).  Not the best behavior, but there are some that will do this.

**Comment by mikeprimm** [comment]
From your original log, I'd pay attention to the line:

 java.io.FileNotFoundException: .\world\level.dat_new (The process cannot access the file because it is being used by another process)

This is a very big deal - the level.* files under world data are critical files, and MC not being able to write/update them, even during shutdown, is pretty darn huge problem.  Dynmap doesn't access them, but I could see tools like world backup tools or world editors doing so - the other classic reason to see an error like this is that a second server instance is running (whether started after the first, or due to an incomplete shutdown from a previous run), both of which are ways to potentially mangle world data.

**Comment by smmmadden** [comment]
@vic197 - related to the error with AnimatedFrames, the developer just updated AnimatedFrames and MapManager resources to 1.13.x. Give those a shot to see if it at least fixes that bug.
