### ISSUE TITLE
Stop Prefixes from appearing on Dynmap? 

### ISSUE THREAD

**Issue by Bowbuck2** [webbukkit/dynmap#2328]
Hello, I am just wondering if i am able to stop Prefixes from Luckperms to stop displaying in the web browser, i am also using essentialsXchat

![capture](https://user-images.githubusercontent.com/12821048/45254539-1835db00-b348-11e8-9139-d655c8bae6da.PNG)

**Comment by mikeprimm** [comment]
Right now, it displays what is know as the 'Display Name', which allows for things like prefixes and nicknames.  I could add an option to only show the 'Account Name', but this would lose any modifiers that are applied (aliases, colors, prefixes, suffixes).  Otherwise, it gets a bit more complicated, since I'd need to give you a way to tell me what exactly to strip off (e.g. like a regular expression, if you are familiar with what that means).

Are you on Spigot or Forge?
