### ISSUE TITLE
Flowerpot rendering broken

### ISSUE THREAD

**Issue by EleRas** [webbukkit/dynmap#2334]
Hi,

The rendering of flowerpots is broken in 3.0-SNAPSHOT-130:
![screenshot_20180910_113553](https://user-images.githubusercontent.com/820659/45289528-ae573600-b4ed-11e8-869f-d9b4c153d3d3.png)
Upper part of picture in-game, lower part dynmap.

**Comment by mikeprimm** [comment]
Fix in next dev build (132)

**Comment by OverCrave** [comment]
Do I need to delete and let dynmap recreate some kind of files because I tried this and it doesnt seem fixed (see https://map.mcbaugrube.de/?worldname=Freebuild&mapname=surface&zoom=9&x=125&y=64&z=-131 for reference). That map uses the last dev build as of this moment (I build dynmap myself using gradle clean build install) and is being rendered right now. You can see there that flower pots and trap door orientation and such is still acting up.

**Comment by EleRas** [comment]
Build 3.0-SNAPSHOT-132 fixed it for me after a radiusrender of the corresponding parts

**Comment by smmmadden** [comment]
because the bug was fixed in the newest version for rendering.  You'll need to download the latest jar file, add it to your server, restart and then regenerate the area(s) that are in question.  If it is visible in select areas, you can use the /dynmap radiusrender option to render only that section.  Otherwise, a fullrender or updaterender is required.

**Comment by OverCrave** [comment]
Did anyone read my messages?
I deleted all the tiles from my database.
Then I compiled the newest version myself and put it into my plugins folder.
Then I let the map generate with the newest version.
The map IS ALREADY in the newest version, the one you see in my link.
