### ISSUE TITLE
Vanilla worldborder not showing 1.13.1

### ISSUE THREAD

**Issue by eightbitx** [webbukkit/dynmap#2338]
The `configuration.txt` setting `showworldborder` doesn't seem to do anything. Can not see the vanilla worldborder on the map. Open issue from 2015: #1860

**Comment by eightbitx** [comment]
@smmmadden As the title says, I'm talking about the **vanilla** worldborder, **not** the WorldBorder plugin.

Also:
**Dynmap version:** core=3.0-beta-1-129
**Server version:** git-Paper-"1b0c2734" (MC: 1.13.1)
**Map version:** Created using 1.13.1

**Comment by eightbitx** [comment]
Is that not what `showworldborder: true` is for? I'm almost certain if you set that value to false your WorldBorder plugin's border will still show.

**Comment by MarioVerbelen** [comment]
I'm also using the vanilla worldborder without plugin, so I'm watching to this issue :)
>worldborder get
[09:29:28 INFO]: The world border is currently 6000 blocks wide

**Comment by Beaupedia** [comment]
Wondering the same thing. It's on but we don't see it.

**Comment by cjucoder** [comment]
Same issue, vanilla world border not showing on dynmap.  Using Spigot 1.13.2 on a map generated fresh with that server version. Very few chunks have been generated by Minecraft yet since it's a brand new map (doubt that's relevant but want to give as much info as possible).  Here is dynmap loading in the server log to show the version...
-------------------------------------
[dynmap] Loading dynmap v3.0-beta-2-138
[16:30:45] [Server thread/INFO]: [dynmap] version=git-Spigot-2474d93-ca22de3 (MC: 1.13.2)
[16:30:45] [Server thread/INFO]: [dynmap] Mod Support API available
---------------------

copy/paste from dynmap's configuration.txt, "true" appears to be default as I did not alter the value
--------------
# (optional) show world border (vanilla 1.8+)
    showworldborder: true
-------------------------------------------------------

**Comment by cjucoder** [comment]
Sorry about the strange formatting in the post, not intentional

**Comment by mikeprimm** [comment]
Just finished fix for vanilla borders in 1.13 - in latest dev build https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar

**Comment by cjucoder** [comment]
Thank you so much! A border is in fact showing now, but in the incorrect position, in fact double the position.

All following coordinates rounded.

My border is set to 12000 blocks diameter centered at 3000, 500 (custom spawn)

`08.12 02:41:37 [Multicraft] cjucoder05@yahoo.com ran command: worldborder get`
`08.12 02:41:37 [Server] INFO The world border is currently 12000 blocks wide
`

actual borders at -3000 west (x neg), 9000 east (x pos),  -5500 north (y neg), 6500 south (y pos)
dymap rendering at -9000 west (x neg), 15000 east (x pos),  -1500 north (y neg), 12500 south (y pos)

See yourself 
[http://mc.gnarcraft.com:8500/](url)

**Comment by MarioVerbelen** [comment]
Thank you so mutch Mike,

My border is 2 time to big
I think you need to take the half of it
http://rocky-map.verbelen.org/
`worldborder get
[09:29:28 INFO]: The world border is currently 6000 blocks wide`

**Comment by MarioVerbelen** [comment]
installed, and it works like expected :)

**Comment by cjucoder** [comment]
Yeah I assumed it was a diameter vs radius thing. Installed. Fixed. Thank you for fixing so promptly!
