### ISSUE TITLE
Terraqueous Blocks Missing

### ISSUE THREAD

**Issue by Enverex** [webbukkit/dynmap#2350]
Running the latest version of Dynmap with BlockScan seems to be working fine for the most part, but any blocks added by Terraqueous are simply invisible. In this screenshot you can see a lot of leafless trees in the top half. They should be various reds, oranges and yellows as it's the Autumnal Woods biome.

![image](https://user-images.githubusercontent.com/958670/46025598-3ab64b00-c0e1-11e8-8ea4-c6e5077b9571.png)

Additionally the grass in the biome in the bottom right should have a slightly turquoise hue to it but it appears as normal coloured grass.

I was under the impression BlockScan should handle this as it does with other mods but it doesn't seem to be. Do I need to change something or does support need to be added to Dynmap?

**Comment by generrosity** [comment]
BlockScan supports mods that use the standard rendering models. Any mod that uses different rendering doesn't appear typically. 'Chisel' is particularly bad for this.

You could confirm using a world with only dynmap/scan + Terraqueous. Unfortunately, if it doesn't work, it likely isn't fixable from this end by the one dev focused working on 1.13.

Otherwise, thanks for your patience, and looks like a nice world you have there~!
