### ISSUE TITLE
Any HTTPS options?

### ISSUE THREAD

**Issue by SJang1** [webbukkit/dynmap#2369]
I have finding if there is any of the https options to use https on dynmap I can't find it.
Is there anyway to use https protocol on dynmap? (Trying to use in windows)
If there not, can you add it to dynmap settings? (I have no technic to do(program) that, but can get a certification.)

**Comment by DmitryRendov** [comment]
ReverseProxy+LetsEncrypt works like a charm for me ([example](https://gist.github.com/DmitryRendov/1efb672a0733aca5314dc3332d9823ac)).

Also - https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-apache2-under-Debian and #2071, #2122

**Comment by SJang1** [comment]
So, Can't I use without Apache (like that)?

**Comment by NatoBoram** [comment]
You can also use Nginx to achieve that.

```nginx
        # DynMap
        location /dynmap/ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://localhost:8123/;
        }
```

**Comment by NatoBoram** [comment]
Of course not, DynMap is not a web server itself. It has one to serve content on its own, but it's not a full-blown web servers that can handle HTTPS.

You'll need to install a real web server that can handle HTTPS, and that web server will redirect traffic to DynMap. This creates a secure communication with your clients on HTTPS, but the internal connection inside your web server will use HTTP, which won't be a problem because it stays on your machine.
