### ISSUE TITLE
Setting dynmap under windows10 apache2.4 server 404(not found)

### ISSUE THREAD

**Issue by SJang1** [webbukkit/dynmap#2393]
I have did [This](https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-Apache-httpd-under-Arch-Linux) and dynmap comes out but no map
I saw network stats, there was 404. What do I have to do to set on Windows?
![image](https://user-images.githubusercontent.com/29011440/49326678-37d04e80-f599-11e8-9bd0-29a53ccc272e.png)

**Comment by Psy-Virus** [comment]
This is clearly a support question. Not an issue. Do we have a support forum? Maybe something like a Google Groups Group would be a good thing. Or @mikeprimm, are you up to host a phpbb support forum? Just thinking because you seem to have a web server and the dynmap domain^^
I mean this issue tracker gets hammered with support questions...

**Comment by Psy-Virus** [comment]
@mikeprimm, well that are only single threads, really hard to keep up with answers. That's probably one of the reasons, why This Issue Tracker is hammered with support questions.
Would you be interested in setting up a phpbb board? It's been developed for quite some time, based on php and open source.
And there's a quite big community.
If you want to take a look: https://www.phpbb.com/

**Comment by mikeprimm** [comment]
If you, and any other mods, would like to see something like a dedicated forum and wiki, for example, I'm game with setting it up.  It's all easy enough to do, and I've got the hosting and owned domains to go with it (e.g. we could have a http://forums.dynmap.us in no time).

**Comment by Psy-Virus** [comment]
U got a YES from me :D
It would make things a lot easier for the whole community, I guess.
This way, the community has a place to ask for support and you can focus on real issues and don't read "I got a 404, How do I do this and that, and so on" for the thousands time. Except you really want it. :D

I'd also do the mod stuff there. And if you want also a Board Admin. I worked with PHPbb before and it shouldn't be a problem for me to handle that.

The only things then were that all places where Dynmap is presented have the Forum linked with some sentence that tells the users to hammer the forum with support questions instead of the GitHub Issue Tracker. :)

**Comment by mikeprimm** [comment]
Right - it'd be good to have it separated from the code management here, since it'll be a lot easier to give roles to you guys and others over there without getting in to any concerns with push privileges or the right (github's privilege control is kind of overly simplistic).

**Comment by generrosity** [comment]
Nice. Psy has phpbb got any more polished over the years? I think my experiences with it have been were the admins were too afraid to add extensions to make life easier like variety of login helpers and customizing the look so it is a bit smoother, and email notifications with actual content. 😋

**Comment by Psy-Virus** [comment]
Well, that just depends on the admins. phpbb is just the base forum software. The extensions and the looks are ofc handled by the admins.

**Comment by Psy-Virus** [comment]
Closed because of support question.

@SJang1, if you need further support, please head over to the mentioned Support Forum at https://forums.dynmap.us

Thanks
