### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by Altijdmax** [webbukkit/dynmap#2436]
Hello I'm Max and I would like to know how I get my map full rendered because it's a judge map!

**Comment by Psy-Virus** [comment]
Hello I'm Psy, and I would like to inform you that this is not a support forum. It is an issue tracker. It is meant for reporting bugs, crashes, other serious issues and feature requests with or for Dynmap. That's what the templates for, from which you can choose, when you try to create an issue.

Please head over to https://forums.dynmap.us because that's a support forum! ;)

Thanks and have a nice day!
