### ISSUE TITLE
RenderData/modsupport folder deletes/reset

### ISSUE THREAD

**Issue by krakah** [webbukkit/dynmap#2487]
## Server Information

- I can reproduce this issue consistently
     - [x ] In Multiplayer 
     - [x ] After deleting/renaming the DYNMAP folder
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x ] Re-rendered missing chunks using /dynmap fullrender
     - [x ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x ] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

/dynmap/renderdata/modsupport folder does 1 of two t hings:

1. with dynmapmodscan enabled will reset any textfile in the renderdata/modsupport folder erasing any custom additions
2. without dynmapmodscan enabled will delete any text file present in the renderdata/modsupport folder erasing any custom additions

## Reproduce Steps
1. Restart Server
2. or run command /dynmap reload
...

## Additional Information

https://pastebin.com/h1wNZrKV

**Comment by mikeprimm** [comment]
Yep - that's a works-as-designed: you can put files you don't want cleaned up in just the RenderData folder.  The modsupport subfolder is used in support of mods that use the dynmap API to describe their blocks (basically, the API calls generate the files on the fly in the scratch space, so that they are then loaded when Dynmap finished loading).  Files anywhere in the Renderdata tree will be processed - but the modsupport folder is specifically for internal use
