### ISSUE TITLE
Dynmap Https Idea

### ISSUE THREAD

**Issue by Xeraccoon** [webbukkit/dynmap#2542]
for the problem dynmap https, we need add use distant ftp for the web folder, or/and use bdd SQL serveur distant

**Comment by mikeprimm** [comment]
easiest option for most folks is to use external web server (nginx, apache), and configure it for https.  We do support storing tiles into a database, and installing the external web files remotely from the server (basically, so that the PHP files on the server talk to the remote SQL, and so does the plugin).
