### ISSUE TITLE
Secure connection

### ISSUE THREAD

**Issue by HoYa-DaiBo** [webbukkit/dynmap#2574]
Unable to provide secure connection

error cord :
ERR_SSL_PROTOCOL_ERROR

[WARNING] Enabled plugin with unregistered PluginClassLoader dynmap v3.0-beta-5-218

[INFO] [dynmap] Starting Scheduled Write Job (markerAPI).

[INFO] [dynmap] Using GroupManager 0.2.0 for access control

[INFO] [dynmap] Mod Support processing completed

[INFO] [dynmap] Loaded 25 shaders.

[INFO] [dynmap] Loaded 82 perspectives.

[INFO] [dynmap] Loaded 14 lightings.

[INFO] [dynmap] Web server started on address 0.0.0.0:8159

[INFO] [dynmap] version 3.0-beta-5-218 is enabled - core version 3.0-beta-5-218

[INFO] [dynmap] For support, visit https://forums.dynmap.us

[INFO] [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues

[INFO] [dynmap] Loaded 3 maps of world 'world'.

[INFO] [dynmap] Loaded 2 maps of world 'world_nether'.

[INFO] [dynmap] Loaded 2 maps of world 'world_the_end'.

[INFO] [dynmap] Enabled

**Comment by MartinFerenec** [comment]
+1
They need to add support for HTTPS as soon as possible

**Comment by rautamiekka** [comment]
+1. Doubt it'd be too much of a problem once started. Besides, I'm sure there have been bigger problems to implement than HTTPS.

**Comment by FedUpWith-Tech** [comment]
jetty isn't a fully fledged webserver, nor is it meant to be. Dynmap supports using external webservers which can support https

**Comment by zefir-git** [comment]
Jetty does support SSL. Not everyone has the access to install a web server on their Minecraft hosting container (esp shared hosts), especially if only because of the SSL. Newer browsers start to enforce HTTPS only rules. For instance my Chromium 87.0.4280.88 absolutely refuses to load Dynmap over HTTP, redirects to https (server is not configured to do that, this is browser-side) and prompts `ERR_SSL_PROTOCOL_ERROR`.
Is there any reason in particular why this would be a bad idea to add, or why it cannot be supported?

**Comment by FedUpWith-Tech** [comment]
@williamd5 jetty does support ssl however it is not designed to be a fully fledged webserver. It works for dynmap but due to many people using dynmap on server hosts natively supporting ssl would create way too many headaches. 
SSL requires binding to port 443 and many hosts use shared ip's* this would stop way to many people from using it and then get mad at us for their host's setup.
Edit: forgot a part

. Https doesn't add any security to dynmap but those that want it still can add it by using an external webserver or reverse proxy

**Comment by zefir-git** [comment]
@FedUpWith-Tech You can bind HTTPS to any port. 443 is only the default, but can be modified on most web servers (I am not aware whether this is supported on jetty, however). It may not add any additional security, but it wold certainly make Dynmap more accessible to people with modern browsers. Do we need to wait until all browsers start requiring HTTPS? A reverse proxy just for dynmap ssl, come on! If you were to set up a server, wouldn't you just host your Minecraft server on that, instead of shared hosting?

**Comment by FedUpWith-Tech** [comment]
Dynmap is perfectly accessible to all modern browsers, modern browser will not stop supporting http

Its incredibly bad practice to bind ssl to anything but 443 and modern browsers will flag that as an error or require a port which defeats the purpose

Edit for clarity: I am using ssl and https interchangeably I know they are different

**Comment by zefir-git** [comment]
![Peek 2020-12-21 23-25](https://user-images.githubusercontent.com/66572326/102823642-f317ea00-43e3-11eb-9c4a-5fb3fa50e210.gif)
Chromium 87 does not. I have had this issue on Chrome as well.

**Comment by FedUpWith-Tech** [comment]
That error shows that you have hsts forwarding not that http isn't supported

**Comment by zefir-git** [comment]
No, the server is not configured to redirect HTTP to HTTPS. This is handled by the browser, default settings. I am able to establish a connection via CURL on HTTP, no SSL.
Version 87.0.4280.88 (Official Build) snap (64-bit)
Ubuntu 20.04 LTS

**Comment by FedUpWith-Tech** [comment]
HSTS forwarding is not the same as HTTP to HTTPS redirection
https://www.globalsign.com/en/blog/what-is-hsts-and-how-do-i-use-it

If you opened an incognito tab and navigated to the website over http BEFORE you navigate to it on https it will work. Once you navigate to it on https once it will only ever let you use https till the enforcement timer expires (usually 1 year)

**Comment by FedUpWith-Tech** [comment]
I can access your map on http on the latest chrome build. Version 87.0.4280.88 (Official Build) (64-bit) Windows
