### ISSUE TITLE
Dynmap really update skin faces?

### ISSUE THREAD

**Issue by pyro000** [webbukkit/dynmap#2599]
I have a plugin who changes skins and got it to work with dynmap in configuration.txt.
The problem is when the skin loads once it never updates again.
Maybe I'm missing something in the config. Thank you.

**Comment by FedUpWith-Tech** [comment]
dynmap only fetches skins once. You can force it but this isn't really the design of the plugin

**Comment by fajfer** [comment]
Hey, @FedUpWith-Tech thanks for the answer but how do you really force it later on? And what do you mean it isn't the design? It it's cached somewhere I'm pretty sure you can just compare the checksums of remote vs local files

**Comment by FedUpWith-Tech** [comment]
> Hey, @FedUpWith-Tech thanks for the answer but how do you really force it later on? And what do you mean it isn't the design? It it's cached somewhere I'm pretty sure you can just compare the checksums of remote vs local files

@fajfer  [It is an option in configuration.txt](https://github.com/webbukkit/dynmap/wiki/Configuration.txt#refreshskins). This does require a server restart which is why I say Dynmap isn't designed to update player skins. 

While yes it is easy to check "is skin current" it is not part of the plugins design, due to the relative stagnation of the plugin's development (only patches to support major releases or community PR's) there isn't any real direction for the plugin in regards to future plans

**Comment by RuofengX** [comment]
I found bug in this feature.
Even I restart server, the skin didn't refresh.
BUT my skin server's nginx log shows that the dynmap server's IP request the face.png file, which is not showed on the map.
nginx log:
`175.27.160.37 - - [29/Jul/2021:03:27:27 +0800] "GET /avatar/player/Iris?size=16 HTTP/1.1" 200 498 "-" "Java/16.0.1"`

---

### Dynmap Configuration:
`fetchskins: true `
`refreshskins: true`
`skin-url: "http://175.27.160.37/avatar/player/%player%?size=32"`
### Example
Skin server API:
[http://175.27.160.37/avatar/player/%player%?size=32](http://175.27.160.37/avatar/player/%player%?size=32)
Dynmap MySQL_marker.php API:
[http://175.27.160.37/map/standalone/MySQL_markers.php?marker=faces/32x32/Iris.png](http://175.27.160.37/map/standalone/MySQL_markers.php?marker=faces/32x32/Iris.png)

---

Don't know how to fix.
