### ISSUE TITLE
Cant connect to website

### ISSUE THREAD

**Issue by DeividKirchev** [webbukkit/dynmap#2685]
Hello, I'm using server.pro. I installed Dynmap changed the config and I can't connect to the website.
1.12 Minecraft version
Bukkit
![image](https://user-images.githubusercontent.com/58637632/70379191-251df180-1932-11ea-96f5-9575a041a4dd.png)
51.255.76.240:7890 <-- This is where the map should load

**Comment by DeividKirchev** [comment]
I reset the server and tried running the plugin on an empty one. Everything loads perfectly with no errors, but I still can't connect to the webserver. I'm trying to run a server with friends on the SMP earth map I need the plugin with the addon so the territories are visible.

**Comment by mikeprimm** [comment]
99% likely to be a firewall setup issue on your server, and opening up the port in the firewall is outside the scope of the application (it depends on your OS, specific firewall software, and/or possibly your hosting and network firewall and routing).   The simple answer is 'you need to do the same think that it took to get your Minecraft server port to be accessible' - if that was done by someone else (e.g. your hosting company), then the answer is likely that you need to engage them to do it.  Otherwise, if you did it yourself, just follow the same procedures for the port number you selected for Dynmap - TCP/IP port are TCP/IP ports: nothing distinctive about the port of an MC server or a web server (whether dynmap's internal one or an external one)/
