### ISSUE TITLE
Dead Project

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [webbukkit/dynmap#2693]
No pull requests are merged, issues aren't answered, DynMap is still on beta with the worst configuration system ever made.
Is this project dead?

**Comment by BlipRanger** [comment]
I don't think it's dead considering that there was a commit just less than a week ago. I'm sure the author is just busy and maintaining stuff like this probably isn't a priority. You could always fork the project if you'd like to maintain it.

**Comment by MJRLegends** [comment]
lol

**Comment by partydev** [comment]
How did you create this issue with a straight face? 1.15 has been out for 3 days. The maintainer of this project has made commits within the past 7 days. This project is far from dead. There is nothing wrong with the configuration.

**Comment by KingHorse2015** [comment]
Look in the open 1.15 issue. The updates of minecraft did change a lot, which requires a lot of time from devs that have chunk based plugins. Be patienced!

**Comment by fichdlmaa** [comment]
Don't forget that dynmap is NO Premium Plugin: You don't have to pay for it! Be patient! 
I think everyone prefers having fun instead of a burning brain in front of his pc screen :lol:

I use DynMap Beta 6 (not 5!) since Oct, 21st. Yes: It has got "black wholes", but it works! 
As for me, combined with world border fill command to get rid of the black areas, it's ok!

But I prefer a improved Version for 1.14.4 instead of a bad 1.15 xmas release !!!
