### ISSUE TITLE
Interest in developing a Fabric mod for 1.15.x

### ISSUE THREAD

**Issue by magneticflux-** [webbukkit/dynmap#2697]
I'm interested in making a Fabric version in the same style as the existing Forge mods. How should I structure it to use the shared APIs? Are they published in a maven repo somewhere that I could use?

I don't think it would be possible to include that build in this repository, but have you considered using Gradle Composite Builds instead of a monorepo with project dependencies?

**Comment by mikeprimm** [comment]
Honestly, having multiple repos for years was a nightmare, and I'd definitely not go back to it.  That said, the build still produces multiple artifacts, including the common core module that is 95% of the code and data content of dynmap (DynmapCore), so that component is importable into another build.

**Comment by magneticflux-** [comment]
Are the artifacts published on a Maven repo somewhere? It looks like some of them are [here](http://repo.mikeprimm.com/us/dynmap/), but that seems out-of-date.

**Comment by magneticflux-** [comment]
@mikeprimm It looks like your artifact publishing configuration is completely missing right now. `publish` and `publishToMavenLocal` are always up-to-date because there are no publications defined. Are there plans to make drastic changes, and/or would you accept a PR that gets artifacts published again?

I have parts of Dynmap working with Fabric on 1.15.1, but I'm running into issues/oddities with the builds from August 2018 (18 months old now).

**Comment by magneticflux-** [comment]
I have the webserver working now, but no tile rendering yet. The implementation of `DynmapServerInterface` for Fabric is bare-bones currently.

![image](https://user-images.githubusercontent.com/9124288/71628571-3c14d400-2bbe-11ea-96b8-e8288d167aff.png)

**Comment by LarveyOfficial** [comment]
Any Updates on this or has it been dropped?

**Comment by magneticflux-** [comment]
@LuisVervaet I haven't made much progress beyond what I showed here, but I made a repo for what I have: https://github.com/magneticflux-/dynmap-fabric

**Comment by LarveyOfficial** [comment]
Awesome! I'm exited to see if this can be done!

**Comment by Martmists-GH** [comment]
Update: development has moved over to [Essentials for Fabric](https://github.com/nyliummc/Essentials/Essentials)

**Comment by FedUpWith-Tech** [comment]
Is the author still working on this port? The repo hasn't been updated recently

**Comment by Martmists-GH** [comment]
After a bit of a talk with mikeprimm in #3027 we have decided to drop the port on our end. We may open a PR in the future, but unplanned for now. The code for our implementation will be available as MIT, or CC0 if reused in dynmap itself.

**Comment by lhns** [comment]
I made a working fabric port for 1.16.1: https://github.com/LolHens/dynmap-fabric
It is pretty new so you might encounter bugs.
Also it is explicitly marked as unofficial so please report any issues in the dynmap-fabric repository and not here.
If there is interest I would love to contribute this as a PR to the official repository.

**Comment by mikeprimm** [comment]
@LolHens That's exciting news!!   I appreciate you marking it as unofficial - let's see what we can do about that :)

What I'd like to propose is one of the following:
- If you want to do a PR into the official repo, that'd be fine - stitching the gradle into the 'one huge' gradle run we do now might be a hassle, but we could add it (at least initially) as a second gradle build done within the same repo after the first one is executed (that is, so that DynmapCore and the like are already built, and then the Fabric build can just leverage those local artifacts).
- Let me stitch your code into the repo - I need to come to know the code, both reviewing it and to be able to 'care and feed' it (although your continued support is welcome!), and that could be a good exercise.  

I'm not sure which seems like the best option to you, but I very much appreciate your labors on this!  I know how much work it is to do an initial platform port, and I wrote the damn code :)

**Comment by lhns** [comment]
@mikeprimm Thank you very much for your positive response! I will put together a pull request with separate gradle files.

**Comment by mikeprimm** [comment]
This all looks very promising - here's my plan:  I'm tryin to get 3.1-beta-3 tested and released tonight.  What I want to do is pull in this PR for this right after I get that release 'in the can' - goal will be that it'll be part of 'beta-4', and that'll give us some time to iron out any missing features and so some real testing before dropping it on the world :)

**Comment by lhns** [comment]
Sounds great! A few people already tested the unofficial version and reported bugs most of which are already fixed.

**Comment by mikeprimm** [comment]
Just merged the PR from @LolHens into the v3.0 branch, and I'll be producing the first formal 'SNAPSHOT' builds today.  I'll post here when they are available - I'd VERY much appreciate it if any of the folks interested in the Fabric 1.16.1/1.16.2 snapshots give these a spin: they are based on the merged code, but we do need to confirm that the merged code built using my processes are at least as good as what has been made available otherwise.  I'm hoping for these to be part of 'beta-4', which I'm targeting to drop next weekend.

**Comment by mikeprimm** [comment]
Snapshot builds available at https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-fabric-1.16.2.jar, https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-fabric-1.16.1.jar .  These builds depend upon the latest fabric-api also being present, so be sure to include those.

**Comment by FedUpWith-Tech** [comment]
There is support for this added now and available for download at https://dynmap.us/builds/dynmap/
