### ISSUE TITLE
Standalone PHP files don't verify X-Forwarded-For

### ISSUE THREAD

**Issue by baconwaifu** [webbukkit/dynmap#2764]
The MySQL standalone webchat php files don't check the `trusted-proxies` config item, and instead implicitly trusts all X-Forwarded-For headers without authentication.

The relevant bit of code is here:
```php
	if(isset($_SERVER['HTTP_X_FORWARDED_FOR']))
		$data->ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
```

**Comment by mikeprimm** [comment]
This is a function of the web server configuration, not the application (it is in the internal server because we are supplying the web server there).
For Apache, use mod_remoteip to implement trusted proxy policy for all purposes (not just one PHP script of ours) - https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html
