### ISSUE TITLE
DynmapForge - Missing Block Textures

### ISSUE THREAD

**Issue by ApertureDevelopment** [webbukkit/dynmap#2806]
Hello,

I am having a issue with DynmapForge with Missing block textures from mods. I know there is Dynmap-Blockscan, but it crashes everytime when we start the server ( after 30 Minutes of scanning blocks ). 

Is there a way to add textures of modded blocks, or maybe a update to Dynmap-Blockscan so it won't crash while scanning the blocks? 

Thank you for all replies

**Comment by Krosta8** [comment]
Hello,
I ran the DynmapForge and DynmapBlockScan in singleplayer and renderdata just put in renderdata in server, almost every block is rendering OK.

**Comment by Griefed** [comment]
Which BlockScan did you use and which blocks don't render properly? Do you have issues with grass and leaf textures being gray?

**Comment by Krosta8** [comment]
I used DynmapBlockScan-3.0-SNAPSHOT-forge-1.12.2.jar 
About 99% blocks from IndustrialCraft are invisible on dynmap and some other mods. If you need this exactly, I can try to scan for every block, but it will take a lot of time.
Generally the problem is with IndustrialCraft

Grass and leaf textures was broken for me with older version of BlockScan. With this one, it is OK

**Comment by Griefed** [comment]
I'm having issues getting Natura, Thaumcraft, Tinker's Construct and Biomes O'Plenty grass/leaves/water to work. Currently trying to manually fix BoP grass, but it's proving to be rather trial and error-style.

Out of curiosity: How long would a full scan take you? It usually finishes in a couple of minutes on my end. I'm asking, because I may be doing something wrong when using BlockScan (I've used the same as you), seeing how your scans take a lot of time.

What mods do you use? If any of my aforementioned mods are in use on your side, too, would you be able to provide your renderdata so I can have a look at it and test it on my end?

**Comment by Krosta8** [comment]
I have dynmap in "low-res" and only "surface". Map is 50 000x50 000 and it takes less than 12 hours, I think.
And if you were speaking about blockscan scan, it takes only a few seconds (less than 10 seconds). 

About the mods, I have non of these :D 
I have IndustrialCraft, Applied Energistics and Chisel.

**Comment by Griefed** [comment]
Ah, thanks for clarifying the time BlockScan takes on your end. Same for me, so that's a relief.
