### ISSUE TITLE
[Feature Request] Change ending of configuration files to *.yml

### ISSUE THREAD

**Issue by th0bse** [webbukkit/dynmap#2814]
Currently, all configuration files are formatted as YAML, but use the *.txt ending. This messes up the automatic highlighting of all sorts of editors like Atom, Notepad++, Vim, Emacs and so on..

For me, this happpens independent of the platform, both Windows 10 and Linux.

So, I'd suggest changing the file endings to *.yml or *.yaml, instead of the pretty meaningless *.txt.

**Comment by th0bse** [comment]
I imagine this to be a pretty minor change, since it shouldn't actually impact the way the files are parsed, although this is just a wild guess right now. I think I will have a look into this myself and see if I can submit a pull request myself to maybe include this change..

**Comment by winnipeg21** [comment]
I use Sublime and it auto-detects the syntax and enables the YAML highlighting.

**Comment by FedUpWith-Tech** [comment]
Mike has previously said he won't make non-functional changes like this due to the fact that it requires large amounts of change for little to no benefit when the only maintainer of the plugin (himself) doesn't care about this. 

It would be nice to have but I'm grateful for the continued maintaining of the plugin vs forks that fix this and then stop development days or weeks later
