### ISSUE TITLE
An idea, about bungeecord

### ISSUE THREAD

**Issue by MagmaBlock** [webbukkit/dynmap#2847]
There are some special needs: Can we install dynmap on bungeecord, and let it work?
(Suppose we can't install plugins on bukkit or spigot)
Make the web map like a in game map mod，only rendering the places where players reached
Maybe these ideas can be usefulness to some people, I searched all over the Internet(China) , but didn't find any way to solve this problem

**Comment by jaboy** [comment]
There would be no point in installing Dynmap on the bungeecord.
Dynmap needs access to the worlds in order to render them, which it is unable to access if it is installed on bungeecord.

The closest to this you can get, is installing the web part of the dynmap on an external webserver (there are guides on how to do this in the wiki), but even then, you would still need to install the dynmap plugin on the spigot server in order for it to render the image for the webserver.

So sadly, if you cannot install plugins on your server, then dynmap is not the plugin you are looking for.... sorry

**Comment by D0ublek1ll** [comment]
If only it worked that way mate.
You could technically pull something like this off by making a dynmap proxy.. but I don't think that the people here are interested in that.
