### ISSUE TITLE
Dynmap rendering is weird

### ISSUE THREAD

**Issue by Ant0ny1** [webbukkit/dynmap#2941]
I have preloaded all chunks within a 2000 block area of spawn with chunkmaster and then radius rendered them in dynmap. The map was fine until a few days ago and this happened. Anyone know why this is happening? And how to fix it thanks.
![Screenshot (25)](https://user-images.githubusercontent.com/65314382/82364827-a939d200-99c4-11ea-9110-b6086f0bc736.png)

**Comment by yakitama** [comment]
This problem is occurd in my server too. I use dynmap v3.0 beta 10 on papermc 1.15.2 build 283 and build 300. Dynmap works fine on papermc build 283, but not on build 300.

Other information:
- Ubuntu 18.04 LTS server
- Server assigned RAM 2GB
- Java 11 (OpenJDK)
- JVM assigned memsize (-Xms ans -Xmx) 1280M

thanks.

**Comment by Tsoccerguy3** [comment]
get latest dynmap here , https://dynmap.us/builds/dynmap/ ,

Dynmap-3.0-RC2-spigot.jar

**Comment by yakitama** [comment]
I tried latest dynmap and it works. Thank you.

**Comment by ice-fly** [comment]
Paper fixed: https://github.com/PaperMC/Paper/issues/3386
