### ISSUE TITLE
Rename YAML files to .yaml

### ISSUE THREAD

**Issue by NatoBoram** [webbukkit/dynmap#2961]
I started to open a few files in the plugin's settings, but... the experience is unpleasant, to say the least. Everything is YAML, but it's also all named `.txt`. I started to add a few settings, thinking it was just an exception, but...

```jsonc
{
	"files.associations": {
		// Root
		"configuration.txt": "yaml",
		"custom-lightings.txt": "yaml",
		"custom-perspectives.txt": "yaml",
		"custom-shaders.txt": "yaml",
		"lightings.txt": "yaml",
		"perspectives.txt": "yaml",
		"world.pending": "yaml",
		"worlds.txt": "yaml",

		// Templates
		"nether.txt": "yaml",
		"nether-hi_boost_vhi.txt": "yaml",
		"nether-hi_boost_xhi.txt": "yaml",
		"nether-hires.txt": "yaml",
		"nether-low_boost_hi.txt": "yaml",
		"nether-lowres.txt": "yaml",
		"nether-vlowres.txt": "yaml",
		"normal.txt": "yaml",
		"normal-hi_boost_vhi.txt": "yaml",
		"normal-hi_boost_xhi.txt": "yaml",
		"normal-hires.txt": "yaml",
		"normal-low_boost_hi.txt": "yaml",
		"normal-lowres.txt": "yaml",
		"normal-vlowres.txt": "yaml",
		"the_end.txt": "yaml",
		"the_end-hi_boost_vhi.txt": "yaml",
		"the_end-hi_boost_xhi.txt": "yaml",
		"the_end-hires.txt": "yaml",
		"the_end-low_boost_hi.txt": "yaml",
		"the_end-lowres.txt": "yaml",
		"the_end-vlowres.txt": "yaml",
	}
}
```

I'm pretty sure this is *not* normal. Why not just name YAML files `.yaml`?

Also, unrelated but `markers.yml` requires `%YAML 1.2`.

**Comment by FedUpWith-Tech** [comment]
This has been suggested and someone even made a PR for it awhile back but the dev doesn't have time to maintain or review major changes like this that are non-functional and only cosmetic. Since he is the only one committed to maintaining the codebase for this plugin and it doesn't help him I completely understand. There are workaround to tell editor applications to read files as other extensions.
