### ISSUE TITLE
Web files are not matched with plugin version

### ISSUE THREAD

**Issue by dW2WvwDSXTxQU6G6** [webbukkit/dynmap#2997]
**Setup**
- Paper 1.16 (v.12)
- Dynmap (3.1-beta-1-367)
- Tile location: NGINX virtual host

**Issue**
Updated to 1.16 recently and when entering the website the error below displays.
`Web files are not matched with plugin version: All files need to be same version (3.1-beta-1-367) - try refreshing browser cache (shift-reload)`

**Attempts**
- Tried to refresh client browser.
- Tried to refresh/purge Cloudflare cache.
- Restarted NGINX and similar services.

Is there documentation on how you update a Dynmap instance with external tile location?
_Thanks for making an awesome plugin!_

**Comment by freethemice** [comment]
I get the same error

**Comment by mikeprimm** [comment]
If you copied the web files to the NGinx host, you will need to repeat that process yourself - if Dynmap didn't copy them in the first place, it certainly cannot refresh them.  This is not a problem on the internal server, nor external servers where the web is being serviced from the same directories - any other scenario will be your problem to address, including any issues with cloudflare or other caching services.  If you are using one of the procedures that other folks have published on, for example, using dynmap with SQL and a remote nginx (zero shared files), you will just need to repeat whatever the procedure from there you used to initially do the setup: it's not a procedure I've formally support, just because this sort of thing inevitably happens.

**Comment by dW2WvwDSXTxQU6G6** [comment]
My bad, you are right, sorry for being too hectic.
I did exactly as you said, copied them over, and it all works now.

Thanks!
