### ISSUE TITLE
hey.... why can't dynmap use the world seed for..

### ISSUE THREAD

**Issue by DrBlackross** [webbukkit/dynmap#3038]
for generating a full map, instead of generating as the player runs around... the only thing i have is a little (5 players maybe) server setup for the kids and me at home. i've set the world size in the server.properties conf and a custom seed. why can't dynamp pull that seed and world size number to generate the map in the background?

i can set the nice and threads in linux when firing it up

make it and option in dynamps config.... i use spigot for the server, way easy to drop jars in and run. :)

**Comment by FrankenBobbo** [comment]
Instead of letting the players generate the map, using plugins like [WorldBorder](https://www.spigotmc.org/resources/worldborder.60905/) or [ChunkMaster](https://www.spigotmc.org/resources/chunkmaster.71351/) pre-generate the world for you. Not as easy as what you suggest, but it works.

**Comment by DrBlackross** [comment]
damn.... lol

(kids are kids)

i will let them know

**Comment by FedUpWith-Tech** [comment]
There are some forge mods and webpages that will generate the map for you based on seed alone [MineAtlas is one example](http://mineatlas.com/) Dynmap is different from that as it allows for greater detail, live player rendering, chat, dynamic updates to ingame-builds and much more. One such requirement of that is that it needs to create a tiered render of the map so that you aren't trying to load a 70GB image of the map each time you want to see where a jungle is. Most browsers freak out if an image is over 100MB and at the level of detail dynmap can generate, a moderately sized world could have a map over 50gb. As FrankenBob mentioned you can pre-generate the chunks of a map to get dynmap to render the whole world but that takes time and a relatively high amount of computing power. 

Sorry that there isn't a better solution lol :(
