### ISSUE TITLE
Can't zoom out

### ISSUE THREAD

**Issue by Gregdoesgithub** [webbukkit/dynmap#3074]
Hello, I just created a dynmap, everything's going just splendidly till the rendering have finished, at which point I cant zoom out. I was hoping there's a way for me and the players to do it considering the map is 40k x 40k big. Any help? Pretty, pretty please.

**Comment by FedUpWith-Tech** [comment]
I'm assuming you can zoom in and back out but there is a max which you can't zoom out past. Unfortunately due to the way dynmap works you can't just "zoom out" further. 

There is a way to tell dynmap to render extra zoomout tiles which does allow more levels of zoomout but it does require re-running a `/dynmap fullrender` you can learn more [about this here](https://github.com/webbukkit/dynmap/wiki/Configuring-Maps-and-Worlds-using-dmap)
