### ISSUE TITLE
Licensing is contradictory

### ISSUE THREAD

**Issue by ccfb3ee765a58cae** [webbukkit/dynmap#3094]
[This section](https://github.com/webbukkit/dynmap/blob/55c2edd2cb759d77ba35431de60bd241ba1ecc75/README.md#porting-supporting-other-platforms-customized-dynmap-builds) of the readme is literally just saying "This project is open source, but it's not".

Which is it? You cannot apply _any_ of those first four restrictions with Apache license. Apache is a fully permissive license &mdash; it requires attribution, trademark compliance, a statement of modifications from original work, but nothing else.

**Comment by whalehub** [comment]
> Which is it?

@ccfb3ee765a58cae The restrictions that are imposed by the Apache license are the only legally enforcable ones. Any additional restrictions that the project developers want to impose on the use of Dynmap's code, such as a [prohibition on selling a modified version of Dynmap](https://github.com/webbukkit/dynmap/commit/aafb71f668e10ffb0b23e34b8b74d0e79d24bdfd#diff-04c6e90faac2675aa89e2176d2eec7d8R73), can be safely ignored.

@mikeprimm @mikeprimm-triva Since people are not required to sign a CLA prior to contributing to this repository, relicensing the code under a more permissive license at this point would require you to either obtain the explicit permission of each individual who contributed to this repository in the past decade or to remove all third party contributions from the code base beforehand.

**Comment by mikeprimm-triva** [comment]
> > Which is it?
> 
> @ccfb3ee765a58cae The restrictions that are imposed by the Apache license are the only legally enforcable ones. Any additional restrictions that the project developers want to impose on the use of Dynmap's code, such as a [prohibition on selling a modified version of Dynmap](https://github.com/webbukkit/dynmap/commit/aafb71f668e10ffb0b23e34b8b74d0e79d24bdfd#diff-04c6e90faac2675aa89e2176d2eec7d8R73), can be safely ignored.
> 
> @mikeprimm @mikeprimm-triva Since people are not required to sign a CLA prior to contributing to this repository, relicensing the code under a more restrictive license at this point would require you to either obtain the explicit permission of each individual who contributed to this repository in the past decade or to remove all third party contributions from the code base beforehand.

Well, here's the thing - the APLv2 allows ME to opt to make this repo private at any time, and not have any concern about doing so.  Unless you guys REALLY want me to cut you off from updates, as is MY right, you'll respect my policies.   I don't owe ANYONE updates, support, or the like, and I can discontinuing providing such at my convenience, as the APLv2 does allow me to choose to not make any further mods on an otherwise existing APLv2 code base public, independent of how I choose to distribute or release the artifacts derived from it.  Hence, if I find out about any significant violation of the POLICIES I am presenting here, I can and I will exercise that option.

As I indicated, policies are NOT licenses - license is legal statement of copyright grant.  APLv2 does not allow me or anyone to revoke an existing license, but it does allow me to take my existing APLv2 code private and does not compel me to release future derivative works with the modified source.  My POLICY is that I'm not going to continue offering public source access to future updates and source if I feel that people are acting in a fashion where they are deriving commercial benefit from our work, nor if that action is causing this team to be encumbered with support load, nor if people are using the reputation of this team in order to take advantage of that reputation to introduce spyware, malware, or other inappropriate content into code distributed as if it is being authored by and backed by this team.

**Comment by ccfb3ee765a58cae** [comment]
Thanks for clarification, as these guidelines are overall agreeable, with the amount of malware/adware distribution in the minecraft community and other shenanigans.
