### ISSUE TITLE
Mod Compatability - Multiple Dimensions and Popular Modded Blocks Not Rendering

### ISSUE THREAD

**Issue by Azuriuz** [webbukkit/dynmap#3112]
**Issue Description:** *I have several dimensions and modded blocks that are showing as blacked out regions. I will try to make a comprehensive list of mods that seem to be affected by this, with the more popular mods on top as they will be most helpful for other players as well.*

* **Dynmap Version:** *Dynmap-3.0-beta-4-forge-1.12.2.jar*
* **Server Version:** *forge-14.23.5.2847*
* **Pastebin of Configuration.txt:** https://pastebin.com/1LDGkK5t
* **Server Host (if applicable):** *Titan Nodes*
* **Other Relevant Data/Screenshots:** *I'm using a custom resource pack based on and using many of the textures and mod support from DokuCraft resource pack. Vanilla textures from the resource pack seem to work fine, it's mostly modded ones that have the issue, whether they are retextured or not. No need for screenshots, as you can just view the map itself.* http://185.211.51.106:8192/
* **Steps to Replicate:** *It happens with any of the modded dimensions/blocks listed below;*

**Full Dimension Support Needed:**
*The Aether
The Atum
The Midnight
The Aurorian
Wyvern Lair from Mo Creatures
Anu dimensions from Fossils and Archeology
Dimension Doors assorted dimensions*

**Mods Needing Block Support:**
*Biomes o Plenty (has some support, but the terrain colormaps don't reflect on dynmap)
Dynamic Trees (all trees show as shadows with a black square in the middle, no leaves or wood)
Quark
Ice and Fire
Astral Sorcery
Bewitchment*

I'll add to this list as I find more black spot sources.

 [x ] *I have looked at all other issues and this is not a duplicate*  
 [x ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Have you checked out dynmap-blockscan? It usually generates the block models needed for dynmap rendering.

I have a repo that contains models for now around 80 mods and two different versions although most models are version agnostic.

Will link when Im at my PC later

**Comment by FedUpWith-Tech** [comment]
Here is the repo for the models: https://github.com/FedUpWith-Tech/DynmapBlockScan-Data
Here is the repo for Dynmap BlockScan: http://mikeprimm.com/dynmap/builds/DynmapBlockScan/

**Comment by Azuriuz** [comment]
Oh wow, this is most of the mods! So to scan for the rest of the modded textures,  I just chuck this one in the mods folder? And then what? Sorry I'm not great at the technical stuff, but I'd like to help with some more compatability if I can!

DynmapBlockScan-3.0-SNAPSHOT-forge-1.12.2.jar

**Comment by FedUpWith-Tech** [comment]
Yeah you put it in the mods folder and during startup it will take forever but generate all the model files it needs in `dynmap/renderdata/modsupport` Then I highly recommend moving all those files (while the server is running) to `dynmap/renderdata` then stopping your server and deleting the dynmap-blockscan mod. This will allow them to persist between server restarts. Dynmap-Blockscan is meant to only be run once and will attempt to regenerate all the definition files on server startup, you absolutely can leave it installed but it will turn an already long server startup into an incredibly long server startup. 
Then, if you would be so kind as to create a PR (details in the blockscan-data repo) with all the mods and versions we don't have already then others won't have to use dynmap-blockscan. If you aren't comfortable doing this or can't figure out how I'll have you send me the files and I'll credit you anyways.

**Comment by Azuriuz** [comment]
I think I can try to figure it out, thank you; I'll send you my results either in a little bit or tonight, depending on if I can get it done before work!

**Comment by Azuriuz** [comment]
So I have a large list and files for a few mods that aren't on the list
The issue is I hit start new pull request and it gives me a page without any real options; I've never made a pull request before, I might be doing it wrong please halp >_<;
If you can guide me, I got the files to add for 34 more mods

**Comment by Azuriuz** [comment]
Also the commands confuse me, what do I put in the console if I just want all currently generated chunks/blocks on the map reload; so I can see the changes with the mod instead of some chunks reflecting the change and others not?

**Comment by FedUpWith-Tech** [comment]
Hey sorry, its not super intuitive to create a pull request. 
1. Create a fork of the Repo (its in the top right and looks like this)
![image](https://user-images.githubusercontent.com/7731191/91611542-81ee8b80-e949-11ea-8f78-a2fe0059079a.png)
2. Either clone the repo to your desktop and add files that way or upload directly to github web on your fork.
3. Once you have finished uploading click the Create PR and your fork should show up now.

Once you've done this I'll review it and make sure its formatted correctly then merge your fork back to main and add the mods to the wiki. If that doesn't work or is too complicated I can have you send the files to me via dropbox or google drive or whatever and then upload them directly to main

**Comment by spiral6** [comment]
I will attempt to try to use this for 1.10.2 and see if this works. How were the Chisel blocks generated, by chance? Seems like the master version of DynmapBlockScan doesn't support Chisel (among other mods).

**Comment by Azuriuz** [comment]
That should get the 1.12.2 list a bit more expansive :3

**Comment by FedUpWith-Tech** [comment]
@Azuriuz 
Whoops, your PR is on the wrong repo. You added a PR to your own forked repo, I can't merge it to the master branch without you opening a PR into my repo.

You'll want to merge it yourself (only you have permissions to do so) then go back to the FedUpWith-Tech/DynmapBlockScan-Data repo and create a PR there using your repo as a source

**Comment by Azuriuz** [comment]
I think I did it right this time?

**Comment by Gartosz** [comment]
@FedUpWith-Tech DynMap BlockScan doesn't generate file for FlatColoredBlocks and Chisel&Bits

**Comment by Gartosz** [comment]
And it displays slab from immersiveengineering with just different meta correctly and other not. How to fix it?

**Comment by HonzaVinCZ** [comment]
Incompability with Dynamic Trees still remains. 

Dynmap-3.1-beta7-forge-1.12.2.jar

Tried to use BlockRenderer, moved generated files into dynmap/renderdata and after map purge and full render, there are only tree shadows. 
I have no idea if I do something wrong because someone says that someone managed to render dyn trees leaves in grayscale at least but I can't manage render even that. 

EDIT: Added screenshot
![DynTrees-DynMap-BlockRenderer](https://user-images.githubusercontent.com/29098779/109362497-67ab5100-788b-11eb-9e6e-3c8b313db55a.png)
![image](https://user-images.githubusercontent.com/29098779/109362635-b8bb4500-788b-11eb-93ac-d45789aff5b3.png)

**Comment by generrosity** [comment]
This was orgiinally a problem @Azuriuz  logged and seemed to resolved? Or at least as resolved as it is going to get with minimal fuss 😁

For everyone else - there has been a major release of Dynmap and of block scan too I believe.  

@Gartosz dynmap is unlikely to support FlatColoredBlocks and Chisel&Bits any time soon as they have custom models and generative textures neither we can dig into.
@HonzaVinCZ we would need more info on what mod the leaves are for - potentially the blocks are written with custom models and might be hard to detect with the several methods

**Comment by HonzaVinCZ** [comment]
> This was orgiinally a problem @Azuriuz logged and seemed to resolved? Or at least as resolved as it is going to get with minimal fuss 😁
> 
> For everyone else - there has been a major release of Dynmap and of block scan too I believe.
> 
> @Gartosz dynmap is unlikely to support FlatColoredBlocks and Chisel&Bits any time soon as they have custom models and generative textures neither we can dig into. @HonzaVinCZ we would need more info on what mod the leaves are for - potentially the blocks are written with custom models and might be hard to detect with the several methods

The mod I was using is Dynamic Trees. More specifically those in the screenshot were oak trees generated by Dynamic Trees. I have no idea if there is still that problem because I moved on recreating my modpack from 1.12 to 1.18. One of the last mods I'm waiting for to update is Dynamic Trees so when that happens, I can test it again on 1.18.

**Comment by mikeprimm-triva** [comment]
If anyone is feeling 'bold', there is a major action in progress right now - let's call it 'alpha level', which is an improvement over last week - involving a near rewrite of DynmapBlockScan and significant API additions to Dynmap - for the sake of mod support (currently on Forge 1.14+, but Fabric-enabling of DynmapBlockScan is on the roadmap).  The current Dynmap (https://dynmap.us/builds/dynmap) and DynmapBlockScan (https://dynmap.us/builds/DynmapBlockScan) 3.4-SNAPSHOT builds are available - you need to currently get them as a set, as I'm making interdependent updates and fixes daily.  Pre 1.14.4 DynmapBlockScans have not yet had this work done - I only expect to do it for Forge 1.12.2, but it isn't done yet.

the renderdata from these versions will ABSOLUTELY not work on anything that isn't Dynmap 3.4-SNAPSHOT, so don't try to backport them for use on 3.3. 

In any case, at the end of the day, we are not and will not implement 'compatibility with mod XYZ' - there are too many, and we aren't equipped to do it as well as the mod authors are - so the best that will happen is recognizing limitations of the 'mapped from the blockstate and model files' method (bugs and the like), and otherwise you're on your own there.

**Comment by Technically-Possible** [comment]
![image](https://github.com/user-attachments/assets/8f025eaf-e7fa-48a3-9ece-a30835d612c4)
im having an issue where i did the scan put in the files but it cant render BiomesOp stuff on the map no matter how hard I try 
![image](https://github.com/user-attachments/assets/67ef5269-2247-49ce-b957-ed48b4b7f609)

**Comment by Technically-Possible** [comment]
heres the block its struggling with 
![image](https://github.com/user-attachments/assets/1a1ffee6-d6b7-45f1-b8cb-df634640357d)
