### ISSUE TITLE
Opaque unknown block ? (non transparent)

### ISSUE THREAD

**Issue by ExDomino** [webbukkit/dynmap#3203]
Hello, I would like to ask if there is a way to make that Dynamp render all unknown block in black but opaque (non transparent).
In order that if a house is made from unknown blocks, players that see the dynmap online don't see the house's indoor.
Thank you in advance.

**Comment by isaaclepes** [comment]
You could also see about adding support for the new blocks.  https://github.com/webbukkit/dynmap/wiki/Custom-Block-Definitions

**Comment by ExDomino** [comment]
Yes, but if a house is build with unknown block, they should be opaque in dynmap, not transparent.
The problem is Chisel, these block are not rendered even with Dynmap Scan.

**Comment by isaaclepes** [comment]
Maybe some of these will help you:

Dynmap Chisel 2 Config
Someone's render config for Chisel 2
https://github.com/Zehir/Dynmap-Chisel-2-Config

DynmapBlockScan ( not updated since 1.15.2, but if you can generate the block data on 1.15.2 it doesn't matter)
This might be what you referred to before, Client-mod that generates textures for missing blocks.  You still need the render config above to tell dynmap how to map to the textures made by this
https://github.com/LolHens/DynmapBlockScan

More useful info
https://www.reddit.com/r/feedthebeast/comments/bwa5q6/how_to_dynmap_mod_textures/
https://github.com/webbukkit/dynmap/files/679635/chisel-models.txt
https://github.com/webbukkit/dynmap/files/679636/chisel-texture.txt

**Comment by ExDomino** [comment]
Is there a solution for Dynmap and Chisel on 1.12.2 ?
Even just rendering Chisel Blocks as black opaque would be fine, just not transparent please.
