### ISSUE TITLE
Dynmap gradually reveals chunks

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3221]
Good day,
we have a problem with the dynmap.
Our card was completely black after the world border.
Gradually, however, more and more individual chunks are sporadically uncovered. Without that there was a user. There are already 22 chunks that have been rendered.

![dynmap](https://user-images.githubusercontent.com/35557302/103151489-be5ab880-477e-11eb-89c8-f8fae74252ee.png)

**Comment by VL4DST3R** [comment]
Keep in mind if someone uses the `/locate` command it will cause the game to randomly "sample" map chunks looking for the requested structure, resulting in a similarly dotted generation. I personally haven't noticed Dynmap generating any new chunks on any of my maps (Multiverse server), and I've been using it for a few years now.

**Comment by mikeprimm** [comment]
Dynmap never 'makes' chunks - it renders what is there.   MC will make chunks, particularly due to things like structures/mines/etc, that will exist beyond movement borders implemented by WB or the like.  If WB doesn't prevent these from being created, that isn't a dynmap problem - we only render what exists.  If you configure visibility limits for the given world (in the dynmap config for the world - see the 'dmap' command - specifically the worldaddlimit, worldgetlimits and worldremovelimit subcommands - to define the map 'clipping' to dynmap explicity), we'll use those to ignore chunks outside the intended visible area.  Dynmap doesn't support WorldBorder - WorldBorder just supports dynmap enough to tell us to draw a circle or square.
