### ISSUE TITLE
Black stripes

### ISSUE THREAD

**Issue by AshKiano** [webbukkit/dynmap#3246]
Hi, 
I have a problem with black stripes and black tiles on my dynmap. I have fully generated world by worldborder plugin and 3 times rendered a dynmap and they are still there. Link: http://panda.hostify.cz:49102
How can I repair this?
Thanks

**Comment by masterX244** [comment]
worldborder has a issue when it gets paused and resumed by a server reboot. Due to how 1.13+ does its chunkgen it skips a stripe of partially generated ones. those cause the renderbugs. Only fix is them getting loaded fully. (either with a player or with a different method of chunkloading, player can be bot-ed to teleport-sweep across the map)

For future pregeneration use the chunky plugin since that handles this case correctly

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2485
