### ISSUE TITLE
Not showing skins

### ISSUE THREAD

**Issue by ZappySK** [webbukkit/dynmap#3289]
Hey guys, my dynmap is not showing player skins, my server is running on bungeecord and i have offline mode, this is my configuration but still showing Steve heads, please help me <3
https://pastebin.com/WCKqNjSq

**Comment by ZappySK** [comment]
Please help me!!

**Comment by stepech** [comment]
Hey, IK it's pretty late, but I am just another server owner and I don't really contribute to this repo.
Because you are running server in offline mode, basically most of the skins, if not all, will be Steves (even in-game, not only on dynmap). In the config, watch look for the lines skin-url: (defaults to: "https://cravatar.eu/avatar/%player%.png"), if it doesn't work, try something like https://minotar.net/helm/%player%/100.png or some other website which send image as a response to request.
Another option is to download SkinsRestorer and let it handle it for you. Then you need to delete '#' in fron of skinsrestorer-integration and set the config option to true. Advantage of this solution is that players can set custom skins and even warez players can have some skin, which will show up on dynmap. Disadvantage is getting it to work on Bungeecord, never tried it before, don't know how difficult it can be.
Hope I helped. If you want to discuss in Czech, just look for me on dynmap's discord

**Comment by stepech** [comment]
Also, not connected to your issue, but I've noticed you're trying to set a custom title in "webpage-title" config option. Unless you remove the # in front of it, it won't work.
