### ISSUE TITLE
standalone/config.js is not generated when running through proxy

### ISSUE THREAD

**Issue by sebastianw** [webbukkit/dynmap#3321]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap is run behind an Apache2 Webproxy. Dynmap is referencing non-existing file `standalone/config.js`*

* **Dynmap Version:** *3.1-beta7-449*
* **Server Version:** *Spigot 3028 (MC: 1.16.5)*
* **Pastebin of Configuration.txt:** *Unmodified*
* **Server Host (if applicable):** *Selfhosted*
* **Other Relevant Data/Screenshots:** 
*Apache Configuration:*
```
ProxyPass         /dynmap    http://localhost:8123/
ProxyPassReverse  /dynmap    http://localhost:8123/
```

*Error in Browser:* `GET https://*mydomain*/dynmap/standalone/config.js?_=3.1-beta7-449 [HTTP/1.1 404 Not Found 41ms]`

* **Steps to Replicate:** *Copy Dynmap to plugin folder, start world. Try to open website in browser through apache proxy*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by Tsoccerguy3** [comment]
If your server is behind a proxy then it is not going to be found on localhost , define the the IP and port being used and open that port to allow through firewall

**Comment by sebastianw** [comment]
It's on the same machine. The Website is loading but only showing a blank black site.  Dieser console shows the mentioned js File is missing.

**Comment by mnh48** [comment]
I have had similar issue but I'm running on nginx [using this as guide](https://github.com/webbukkit/dynmap/wiki/Dynmap-with-Nginx-server-on-Centos), but the issue disappear when I use root directory instead

if I set it to load, for example, at `http://example.com/map` (using the appropriate rule for nginx) then the website is loading but only show blank black site, opening the console reveals the error `:37 GET <path>/standalone/config.js?_=3.1-beta7-449 net::ERR_ABORTED 404 (Not Found)`

however, if I set it to load, for example, at `http://example.com` only, instead of trying to use directory (`/map` in my case), then it works, the map do shows up correctly and everything works perfectly

so I'm subscribing to this issue to see if there's something wrong with config.js, and I'm using root directory for time being as that worked for me

Dynmap Version: v3.1-beta-7 (`Dynmap-3.1-beta7-spigot.jar`)
Server Version: Minecraft 1.15.2

**Comment by RainOrigami** [comment]
For anyone interested who has this issue in apache2, the issue for me was that the proxy path I supplied did not end with a backslash.

Bad:
`ProxyPass /minecraft/map http://127.0.0.1:8123/`

Correct:
`ProxyPass /minecraft/map/ http://127.0.0.1:8123/`
