### ISSUE TITLE
Not compatible with Universal Graves

### ISSUE THREAD

**Issue by elhertz** [webbukkit/dynmap#3495]
**Issue Description:** Dynmap is currently not working with the Universal Graves mod for Fabric. I've tested both curseforge latest 1.17.1 version and latest dev-build snapshot. Universal Graves' dev told me that this issue is not something they can fix so I'm reporting this here.

* **Dynmap Version:** `Dynmap-3.2-beta-3-fabric-1.17.1` or `Dynmap-3.2-SNAPSHOT-fabric-1.17.1`
* **Server Version:** `Fabric Server Loader v0.11.7`
* **Pastebin of Configuration.txt:** using default config
* **Server Host (if applicable):** Selfhosted
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/h63JHPmd
* **Steps to Replicate:** Use <ins>Fabric Server Loader v0.11.7</ins> and these mods: [Dynmap-3.2-beta-3-fabric-1.17.1](https://www.curseforge.com/minecraft/mc-mods/dynmapforge) or [Dynmap-3.2-SNAPSHOT-fabric-1.17.1](https://dynmap.us/builds/dynmap/Dynmap-3.2-SNAPSHOT-fabric-1.17.1.jar) - [fabric-api-0.40.1+1.17](https://www.curseforge.com/minecraft/mc-mods/fabric-api) - [graves-1.1.0+1.17.1](https://www.curseforge.com/minecraft/mc-mods/universal-graves)

**Comment by Patbox** [comment]
Hello, Universal Graves and Polymer developer here! This issue is caused by small hack made by Polymer, which should be somewhat simple fix on dynmap side.

So Polymer needs to offset BlockStates of server side blocks as otherwise it caused client side block desync. This is made by replacing buildin ArrayList with special DualList which is more or less 2 ArrayList with an offset. While it works fine with more or less every mod (tested with AOF 4), dynmap seems to not work with it.

There are 2 ways to fix it, either by checking if block implements VirtualBlock interface and replacing it's rendering/target to represented block. Less ideal fix is checking blockState ids and discarding them above a offset used by Polymer, but it makes them invisible for dynmap

**Comment by FedUpWith-Tech** [comment]
@kosma worked on the fabric port, pinging for their visibility

**Comment by Patbox** [comment]
Also if someone has any questions, feel free to ask. I can also try writing a pr, hovewer it should be simple fix anyway (and I have limited time)

**Comment by Patbox** [comment]
Okay, tried to fix that and it would take too long to do so on dynmap side. It's been "fixed" (aka lowered blockState id offset) in latest polymer build. If you want to try it add https://github.com/Patbox/polymer/releases/download/0.1.6/polymer-0.1.6+1.17.1.jar to your mods folder or (ideally) wait for next Universal Graves update

**Comment by Patbox** [comment]
And Universal Graves updated too. You can get the update from https://github.com/Patbox/UniversalGraves/releases/download/1.1.2/graves-1.1.2+1.17.1.jar

**Comment by wolfsprite** [comment]
> 
> 
> And Universal Graves updated too. You can get the update from https://github.com/Patbox/UniversalGraves/releases/download/1.1.2/graves-1.1.2+1.17.1.jar

This latest update is crashing my server (without Dynmap) on startup, can confirm it is your mod as well that is causing it, as server is fine when it is removed. :(

**Comment by Patbox** [comment]
Could you send the crash? From my testing it works just fine with other mods and dynmap

**Comment by Patbox** [comment]
Also this can be closed, as I believe it's resolved (still, dynmap should get rework in that area)

**Comment by elhertz** [comment]
Fixed from Universal Graves' side
