### ISSUE TITLE
hideNames/hidenames should remove the playername from the face tile

### ISSUE THREAD

**Issue by bloctown** [webbukkit/dynmap#3549]
**Issue Description:** *hideNames/hidenames doesnt remove the playername from the face tile*

* **Dynmap Version:** *v3.2.1*
* **Server Version:** *paper-1.17.1-353.jar*
* **Pastebin of Configuration.txt:** *https://pastebin.com/WXr7Duhg*
* **Server Host (if applicable):** *self hosted*
* **Pastebin of crashlogs or other relevant logs:** *n/a*
* **Other Relevant Data/Screenshots:** *n/a*
* **Steps to Replicate:** *Start any server with dynmap running, and set `hidenames: true`. Open any modern web browser and on the player sidebar, then right click > inspect element on a players face. You can ctrl+f for the playername in the inspector tool, because playername.png is what the player face tiles are saved as. I know there is an option to hideplayerfaces too, but I feel like being able to find players by name whilst `hidenames` is true goes against the purpose of it*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by generrosity** [comment]
Just to confirm - you are confirming that ticking the option doesn't rename the image that is displayed on screen? Or something else?

I have a feeling this is a stylistic choice rather than a security one. It might be possibly to obfuscate the image name (there might be proxies that do it).

Is this a specific security feature that you are looking for? Or just observation?

**Comment by FedUpWith-Tech** [comment]
Changing this to be a feature request since this really isn't a bug

**Comment by FedUpWith-Tech** [comment]
Listed in megathread #3461
