### ISSUE TITLE
The dynmap menu (web) no longer works on some maps

### ISSUE THREAD

**Issue by aurel85** [webbukkit/dynmap#3588]
Hi,

* **Dynmap Version:** *31.12 00:48:43 [Server] INFO Dynmap version: core=3.3-beta-4-617, plugin=3.3-beta-4-617*
* **Server Version:** *31.12 00:49:12 [Server] INFO This server is running Paper version git-Paper-112 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 329912b)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/HpciRPT9*

**Issue Description:** 

For some time (during 1.17.1, not at the time of the update) some of my maps have seen their border, marker or other additions (claim) disappear. But this is only done on the second card or the third card in the list, not the first. The left menu where I can enable / disable these options no longer works. I do not understand because the bug happened on its own, I did not modify anything in Dynmap and after my passage in 1.18.1 it is still present. Do you have any idea what is causing this problem? I would like to find my benchmarks and other indicators (for player display everything works).

To visualize for yourself go to https://map.freebuild.fr and look at the servers where there are several cards, compare between the first and the second you will understand (except the Skyblock)

I saw this error with RedProtect (my claim plugin) but it doesn't all depend on this plugin in the bug so I don't really know what to think about it -> https://pastebin.com/5WJKqwr9

No file has been reset in the dynmap folder, the markers still exist for example.

Thank you in advance for your help.

**Comment by FedUpWith-Tech** [comment]
In the error log it shows that the markers are being hidden by default due to an error with Redprotect's Dynmap Integration:
`30.12 20:07:10 [Server] WARN java.lang.NullPointerException: Cannot invoke "org.dynmap.markers.MarkerSet.setHideByDefault(boolean)" because "br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.MSet" is null`

Looks like this bug in redprotect is also causing Dynmap's markers to be broken. Will have to wait for redprotect to fix

**Comment by aurel85** [comment]
With version beta-5 it's corrected, thanks :)
