### ISSUE TITLE
hidestyle: ocean doesn't create blue ocean, rather a grey ocean

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3607]
**Issue Description:** hidestyle: ocean doesn't render with ocean colour

* **Dynmap Version:** core=3.3-beta-4-617, plugin=3.3-beta-4-617
* **Server Version:** git-Paper-148
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/F5h31UR8)
* **Server Host (if applicable):** localhost
* **worlds.txt:** [worlds.txt](https://github.com/webbukkit/dynmap/files/7849890/worlds.txt)
* **Other Relevant Data/Screenshots:** ![image](https://user-images.githubusercontent.com/45831568/149022392-d5731a45-17e2-4d19-a1c1-85c5ab8a791c.png)
* **Steps to Replicate:** install dynmap, set hidestyle to ocean, set visibilitylimits, do a fullrender, see the issue on the map.

 [x ] *I have looked at all other issues and this is not a duplicate*  

 [x ] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Rendering normally in current snapshots.  Fixed by another change that caused those generic sections to also be initialized with a non-null biome (OCEAN for water, PLAINS for stone)

<img width="704" alt="Screen Shot 2022-01-18 at 11 13 44 PM" src="https://user-images.githubusercontent.com/654487/150068414-673e773e-8a63-4f43-a2f9-1e3ff87e6ee8.png">

**Comment by JurgenKuyper** [comment]
tested, and indeed fixed, thanks!
