### ISSUE TITLE
shaders not being rendered as before

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3624]
**Issue Description:** in dynmap 3.3-beta-5, shaders ovocean, ovflames, surface-temperature and surface-rainfall are no longer being rendered.

* **Dynmap Version:** 3.3-beta-5 build 655
* **Server Version:** papermc build 169
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://github.com/JurgenKuyper/Dynmap-setup)
* **Server Host (if applicable):** selfhosting
* **Pastebin of crashlogs or other relevant logs:** nothing to specify
* **Other Relevant Data/Screenshots:** ![afbeelding](https://user-images.githubusercontent.com/45831568/150631939-d122a3d7-0e16-41a4-92af-82e5b1cc16f8.png) seems to be rendering black, you can see the difference here as I just started a fullrender.
* **Steps to Replicate:** render a shadered ovocean and ovflames render in the beta-4 build for 1.18.x, update dynmap to latest, rerender the map, renders black. 

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by mikeprimm-triva** [comment]
"As before" meaning versus when?

**Comment by JurgenKuyper** [comment]
Last version I used before this is 3.3-beta-4-617, was busy so didn't update every build

**Comment by mikeprimm** [comment]
OK - got it - the refresh of the colorschemes to work with 1.18 did not include some of the ones based on long dead resource packs (flames, sk89q, ovocean), and the refresh was needed because 1.18 doesn't have block ID numbers anymore.  I've migrated the obsolete ones to match the standard mapping, and split out the biome, temperature, and rainfall maps so that they don't get smashed when the maps are generated in the future (this is a development action, since it involves getting the RPs and running the mod with a special flag to produce the mapping files).

Try latest beta-5 release canadidate

**Comment by JurgenKuyper** [comment]
yep, the shaders seems to be working again, thanks for the fast fix!
