### ISSUE TITLE
There is no centering

### ISSUE THREAD

**Issue by 1Pootis1** [webbukkit/dynmap#3651]
**Issue Description:** *Hello, I have a problem with the map, you can look at this link in more detail, this is an important problem, did you do something with CSS in the latest plugin updates? Link: https://github.com/TownyAdvanced/Towny/issues/5711*

* **Dynmap Version:** *[v3.3 GA release](https://www.spigotmc.org/resources/dynmap%C2%AE.274/update?update=443468)*
* **Server Version:** *Paper 1.17.1-404*
* **Pastebin of Configuration.txt:** *https://pastebin.com/PLJCgbjX*
* **Server Host (if applicable):** *MajorCore*
* **Pastebin of crashlogs or other relevant logs:** *no errors*
* **Other Relevant Data/Screenshots:** *https://github.com/TownyAdvanced/Towny/issues/5711*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
The \<center\> tag referred to in the original issue is an obsolete HTML4 tag that browsers are stopping support for - likely broke with a browser update vs anything to do with Dynmap.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center.  use \<div style="text-align:center"\> instead

**Comment by 1Pootis1** [comment]
it really works, but can you tell me how to return the lines that were?
![image](https://user-images.githubusercontent.com/73141732/152619394-ee979f63-932a-41a1-9b9f-e657a22e7fe2.png)


`<hr style="border-width:3px;border-color:grey;">`

**Comment by 1Pootis1** [comment]
I just used `<hr>` now and they appeared, but after a few seconds they disappeared again
![image](https://user-images.githubusercontent.com/73141732/152619901-e243144b-c178-43b6-8cbd-3f9bad389937.png)
![image](https://user-images.githubusercontent.com/73141732/152619910-ee25e927-362e-4b6e-931b-04882809d298.png)

**Comment by mikeprimm** [comment]
Found inconsistency in the sanitizer (which is used to protect web users from injection attacks from folks using the markup feature on labels and descriptions.... cannot allow folks to pass in things like javascript or the like) being applied for initial load of markers on a world, and updates (the initial load wasn't being cleansed properly, which was why the obsolete tags were getting through, and then being removed on updates/refreshes).   I've added the \<center\> and \<hr\> tags to the whitelist, since they're old/obsolete, but safe.

**Comment by mikeprimm** [comment]
Tags added to whitelist on v3.3.2 and v3.4-SNAPSHOT (696+)

**Comment by 1Pootis1** [comment]
thx 😊😉
