### ISSUE TITLE
No clean round world since Minecraft 1.18

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3692]
Dynmap Version: v3.4-beta-1
Paper-Version: paper-1.18.1-214

We have been using Dynmap for almost 5 years. Until now we always had a nice round world map.

Since 1.18 where we re-rendered the map because there were problems with the heights on the map and we re-rendered the map, our renders look horrible.

does anyone else have the problem? if so how did you solve it?.

Here is our approach.
We first render the map with Worldborder with the commands:
/wb world fill 20 208
/wb world trim 5000 208

When it's done we stop the server and restart the server.
Then we have a full render made with the dynmap. But unfortunately the same ugly derided card always comes out.

Old map before 1.18

![erde1](https://user-images.githubusercontent.com/35557302/155611381-b65d76e3-e5ad-4cc1-9354-3d3a38ba8885.png)

The map after 1.18

![dynmap](https://user-images.githubusercontent.com/35557302/155611435-67029253-f040-4cde-b9ec-a5d0d0a28213.png)

It just doesn't render a clean border anymore...

**Comment by mikeprimm** [comment]
Cannot blame the messanger for the message - Dynmap doesn't MAKE chunks, it just shows them, and MC has made it so that full chunks that have not yet been migrated to the latest version are indistinguishable from chunks that are not yet full chunks: so you either see some chunks that ARE valid, DO exist, but are not 'final' (full state), or you get black borders between pre 1.18 chunks and 1.18 chunks due to how MC handles the lazy migration of those chunks from being 'full' 1.17 chunks to 1.18 protochunks to full 1.18 chunks.
