### ISSUE TITLE
Dynmap shows black spots on webmap but not when I zoom in

### ISSUE THREAD

**Issue by Golicraft** [webbukkit/dynmap#3700]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Hi, we have some issues with displaying the map correctly on the web. It appears some black "spots"/"chunks". I know that similar issues have been reported, but my case is that if I zoom in almost the most the black spots dissapear.*

* **Dynmap Version:** *dynmap version 3.4-beta-2-761*
* **Server Version:** *git-Purpur-1565 (MC: 1.18.1) - It's an fork of spigot/paper*
* **Pastebin of Configuration.txt:** *https://pastebin.com/PyHZZ03f*
* **Server Host (if applicable):** *Mchost.no*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** *https://imgur.com/a/7FSoCQv*
* **Steps to Replicate:** *I am not sure. I have rendered the world multiple times. I have updatedrender, I have radiusrender. I have teleported to these spots. So for this I think the issue may be that our map is 25 x 25k*

 [V ] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by generrosity** [comment]
If it has the correct detail when completely zoomed in, then it is the 'zoom tiles' that are incomplete. These are automatically generated rather than done with commands, and worked on in the background.  

As I understand, you 'just' need to give it a little more time to generate these for you.

Usually its not too long tho. I think you can look at 'dynmap stats' to see the current progress of zoom tiles being rendered.
