### ISSUE TITLE
web map incomplete rendered region 

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3713]
Hi, I had been working some major edits in my server's building. I wanted to use dynmap for a more accurate view but it seems that the region isn't rendered completely. I thought it may take sometime for it to update but it has been like this for a few weeks. Is there any way that I can solve this issue?

![image](https://user-images.githubusercontent.com/78998867/157804160-00ac0279-b451-4d7f-af70-d5b828f6ecbb.png)

**Comment by JurgenKuyper** [comment]
Did you change the render resolution after the map was rendered?

**Comment by generrosity** [comment]
General answer to most rendering bugs is to do radiusrender / map purge / full render to resolve any visual glitches, particularly if you done any changes to the config since tiles have rendered. It doesn't automatically convert.

Looking at the graphics - looks like youve maybe worldedit sand of one kind to another as the contours are the same - unfortuantely looks like the case where some cleanup rendering is needed is all.

**Comment by generrosity** [comment]
closing as it looks to be a simple case, but happy to see it reopened if having problems with thing :)
