### ISSUE TITLE
SQLException: Tile read error

### ISSUE THREAD

**Issue by Spiderjockey02** [webbukkit/dynmap#3801]
**Issue Description:** My world is generated fine till it gets near the end where it will just produce a black screen (on the website) and if I refresh again it crashes the webserver. There is no errors in the console at all only when I restart or stop the server.

* **Dynmap Version:** *v3.4-beta-4-792*
* **Server Version:** *paper 1.19 version 58*
* **Pastebin of Configuration.txt:** *[https://pastebin.com/5SETL3z2](https://pastebin.com/11jKQR7N)*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/gjFekz6z*
* **Other Relevant Data/Screenshots:** ![image](https://user-images.githubusercontent.com/55885015/179393392-d03b023a-02e0-460b-b651-6243e3e86856.png)
* **Steps to Replicate:** *I am unsure how to replicate*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
interrupted means that the connection between the sqlite database and the server was severed, could be because timeout was expired, I don't know why really.

**Comment by Spiderjockey02** [comment]
yh, I don't really know either, I've made sure it can read and write the files. 
The server has a lot of available space so it's not a storage issue.
It seems to work only when I restart the server, cancel the render and then restart the render. It will work for a bit and then just stop.

**Comment by VL4DST3R** [comment]
This is an issue I've been having for years with `fullrender` commands on (presumably) large worlds. Another ticket about this is #3720. Only way to get a working dynmap after this is to delete the `worldname.pending` file inside the plugin and let it regenerate. You will lose whatever chunks were marked to be updated in there but at least the map will work again. Really wish for a response from a dev about what is happening.

**Comment by MidnightQuery** [comment]
same happened to me, third time already
also after i delete the pending file. when i try to resume render. it just crash
https://gist.githubusercontent.com/huizichin/4fbda411f4d063528bb3db46b755afd3/raw/c94934a9ca78a6b070050fa241fbf16a5d13e26d/error

**Comment by mikeprimm** [comment]
Resume render (which was from a PR about 3 years back that I clearly did not review well enough) was quite broken-by-design.  I'm working to try to fix it now.   I honestly didn't even realize the command existed, and I'm not completely sure why it does (it makes some pretty murky assumptions, like every existing tile MUST already be up to date, which is not right if the 'resumed' fullrender were anything other than a clean/first time one...).

The complaints during shutdown (your screenshot's first line shows 'Disabling dynmap...', which is only when a shutdown is initiated) are noise and ultimately not relevant.  Just means that your SQLite is choking under load (not too shocking - it's really not a good DB) and the pending writes are needing to be cancelled during shutdown in order to avoid the server bitching about shutdown taking too long (pick your poison.... cannot finish writing to an I/O blocked DB during a time bound shutdown operation....).

**Comment by MidnightQuery** [comment]
i migrated to mariadb, since it seem like sqlite is not great for storing pic. hopefully i don't run into as much problem now

**Comment by SCLeoX** [comment]
> This is an issue I've been having for years with `fullrender` commands on (presumably) large worlds. Another ticket about this is #3720. Only way to get a working dynmap after this is to delete the `worldname.pending` file inside the plugin and let it regenerate. You will lose whatever chunks were marked to be updated in there but at least the map will work again. Really wish for a response from a dev about what is happening.

This fixed the issue for me. Thanks.
