### ISSUE TITLE
Option to reuse hidestyle chunks

### ISSUE THREAD

**Issue by Kyrenic** [webbukkit/dynmap#3885]
**Feature Description:** *Chunks that are rendered as a hidestyle should have the option to reuse textures to avoid additional tile bloat.*

* **Additional context:** *On my server I have a vanilla world border set, and I've also defined a visibilitylimits in my world. Chunks outside of that visibilitylimits are rendered as a hidestyle, which I've set to air. Now, I've been told that each individual tile is stored, even if it is outside of the visibilitylimits , I'm worried about my dynmap tile folder becoming very large because of this. Reusing the air, stone or ocean hidestyle for these chunks would decrease the size that the plugin uses greatly.*

Now, I'd propose the following boolean to be added to the world settings:
`reusehidestyle: true/false`

**Comment by JurgenKuyper** [comment]
hidestyle air is just an empty image, of really tiny size, the stone and ocean variants need to be stored individually because on the edges of the fullrenderlimits if using hiddenlimit (inverse of fullrenderlimit) and they intersect on a chunk, you cannot store half a tile as hidestyle and fullrender the other part.

**Comment by Kyrenic** [comment]
Ah nevermind then, my concerns were unfounded, thanks for the quick response, as far as I'm concerned the issue can be closed!

**Comment by JurgenKuyper** [comment]
no problem, better safe than sorry! I will close this issue now.
