### ISSUE TITLE
Put more dynmap icons

### ISSUE THREAD

**Issue by OsGBanzinho** [webbukkit/dynmap#3900]
Hi, I wanted some help on how to add other icons to the dynmap besides the default one

**Comment by JurgenKuyper** [comment]
https://github.com/webbukkit/dynmap/wiki/Using-Markers

**Comment by OsGBanzinho** [comment]
[imagem](https://media.discordapp.net/attachments/722723942111903765/1053712039039737927/Screenshot_11.png) 
Every time I use the command it always says this could show where I'm wrong

the commands I tried to use to add the icon
dmarker addicon id:vila label:vila file:/plugins/dynmap/web/tiles/_markers_/vila
dmarker addicon id:vila file:/plugins/dynmap/web/tiles/_markers_/vila
dmarker addicon id:vila file:"vila"
dmarker addicon id:vila file:vila

**Comment by JurgenKuyper** [comment]
/dmarker addicon id:<id> <label> file:"filename" : Install new icon, with given ID and label, and using given file (path is handled relative to MC server directory, and file contents are copied). so from the server jar on, don't put the first / in as that relates to a absolute directory instead of a relative one.
